# Hybrid LSTM+GAT Fraud Detection — IBM & Sparkov
Standalone companion to *Isolating Graph Topology from Model Architecture in
GNN-Based Fraud Detection* (Amiri & Jaf, University of Sunderland, 2026).
Extends the fixed-architecture, variable-topology framework with three
architecture variants per dataset, holding topology fixed and varying
architecture instead — the inverse experiment.

| File | Architecture | Node granularity |
|---|---|---|
| `<dataset>/lstm_gat_sequential_model.py` | LSTM → GAT pipeline | Transaction |
| `<dataset>/lstm_gat_parallel_model.py` | LSTM ‖ GAT, cross-attention fusion | Transaction |
| `<dataset>/account_gat_homogeneous_model.py` | Unchanged GATv2, new topology | Account |

Run the **IBM** section, the **Sparkov** section, or both — they're
independent and don't share state.

---
### Before you start
1. **Runtime → Change runtime type → T4 GPU** (free tier)
2. Update `REPO_URL` in Cell 2
3. Skip whichever dataset section you don't need

In [3]:
import os
drive_dir = '/content/drive/MyDrive'
remaining = [f for f in os.listdir(drive_dir) if f.startswith(('lstm_seq_', 'lstm_par_')) and f.endswith('.pkl')]
print(remaining)

[]

---
## Cell 1 — Install dependencies

In [4]:
import subprocess, sys
import torch

torch_version = torch.__version__.split('+')[0]
cuda_version  = 'cu' + torch.version.cuda.replace('.', '') if torch.cuda.is_available() else 'cpu'
print(f'PyTorch {torch_version}  |  CUDA: {cuda_version}')

subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'torch_geometric'], check=True)
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q',
                'scikit-learn', 'pandas', 'matplotlib', 'pyarrow', 'faiss-cpu'], check=True)
print('Done.')

PyTorch 2.11.0  |  CUDA: cu128
Done.

---
## Cell 2 — Clone this repo

In [5]:
import os

REPO_URL = 'https://github.com/Roya62/hybrid-gnn-lstm-fraud'  # ← update

if not os.path.isdir('/content/hybrid-gnn-lstm-fraud'):
    !git clone -q {REPO_URL} /content/hybrid-gnn-lstm-fraud

os.makedirs('/content/outcomes', exist_ok=True)
print('Repo ready at /content/hybrid-gnn-lstm-fraud')

Repo ready at /content/hybrid-gnn-lstm-fraud

---
## Cell 2b — (Optional) Mount Google Drive
Only needed if your dataset files live in Drive.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

---
# Part A — IBM Dataset

## Cell 3 — Load and preprocess
Set `IBM_DATA_PATH` to your actual `reduced_dataset.parquet` (or
equivalent) location before running.

In [6]:
import os, sys
import sys

for mod in ['config', 'utils', 'gatv2_model', 'lstm_gat_sequential_model',
            'lstm_gat_parallel_model', 'account_gat_homogeneous_model']:
    sys.modules.pop(mod, None)

import os, sys

IBM_DATA_PATH = '/content/drive/MyDrive/reduced_dataset.parquet'  # ← update

os.chdir('/content/hybrid-gnn-lstm-fraud/ibm')
sys.path.insert(0, os.getcwd())

import config as ibm_cfg
cfg_ibm = ibm_cfg.IBMFraudConfig()
cfg_ibm.OUTCOME_DIR = '/content/outcomes/ibm'

import utils as ibm_utils
df_ibm = ibm_utils.load_and_preprocess(path=IBM_DATA_PATH, cfg=cfg_ibm)
print(f'{len(df_ibm):,} transactions loaded.')

Loaded: 24,386,834 transactions
Downsampled: 29,757 fraud + 297,570 non-fraud
After preprocessing: 327,327 rows | Fraud rate: 0.0909
327,327 transactions loaded.

---
## Cell 4 — IBM: GATv2 baseline (fixed architecture, for comparison)
~25–40 min on T4 GPU (all 3 strategies).

In [ ]:
import gatv2_model as ibm_gatv2

gatv2_results_ibm = ibm_gatv2.run_all_strategies(df_ibm, cfg_ibm)
print('\nIBM GATv2 baseline done.')

############################################################
# GATv2 | multi_relation
############################################################
  Fold 1/5
  [multi_relation] nodes=211,649 edges=916,245 deg(min/med/mean/max)=(1,5.0,4.3,9)
  [multi_relation] nodes=51,829 edges=267,895 deg(min/med/mean/max)=(1,5.0,5.2,9)
     TRAIN | F1 0.823 | P 0.838 | R 0.808 | AUC 0.981 | AP 0.888 | LL 0.2263 | Brier 0.0666
       VAL | F1 0.808 | P 0.834 | R 0.783 | AUC 0.977 | AP 0.874 | LL 0.2415 | Brier 0.0715
  Fold 2/5
     TRAIN | F1 0.831 | P 0.844 | R 0.819 | AUC 0.984 | AP 0.905 | LL 0.2188 | Brier 0.0641
       VAL | F1 0.805 | P 0.826 | R 0.784 | AUC 0.978 | AP 0.883 | LL 0.2509 | Brier 0.0748
  Fold 3/5
     TRAIN | F1 0.824 | P 0.841 | R 0.808 | AUC 0.982 | AP 0.894 | LL 0.2242 | Brier 0.0652
       VAL | F1 0.822 | P 0.843 | R 0.803 | AUC 0.982 | AP 0.893 | LL 0.2396 | Brier 0.0712
  Fold 4/5
     TRAIN | F1 0.829 | P 0.852 | R 0.808 | AUC 0.984 | AP 0.900 | LL 0.2114 | Brier 0.0624
       VAL | F1 0.796 | P 0.822 | R 0.770 | AUC 0.979 | AP 0.873 | LL 0.2394 | Brier 0.0711
  Fold 5/5
     TRAIN | F1 0.827 | P 0.846 | R 0.809 | AUC 0.983 | AP 0.901 | LL 0.1993 | Brier 0.0578
       VAL | F1 0.808 | P 0.822 | R 0.794 | AUC 0.977 | AP 0.877 | LL 0.2331 | Brier 0.0691
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.828 | P 0.882 | R 0.780 | AUC 0.984 | AP 0.908 | LL 0.2215 | Brier 0.0647
  Saved: /content/outcomes/ibm/ibm_gatv2_multi_relation_diagnostics.png

############################################################
# GATv2 | hybrid
############################################################
  Fold 1/5
  [hybrid] nodes=211,649 edges=2,127,771 deg(min/med/mean/max)=(5,10.0,10.1,52)
  [hybrid] nodes=51,829 edges=561,393 deg(min/med/mean/max)=(5,11.0,10.8,52)
     TRAIN | F1 0.795 | P 0.827 | R 0.764 | AUC 0.979 | AP 0.873 | LL 0.2070 | Brier 0.0606
       VAL | F1 0.794 | P 0.825 | R 0.765 | AUC 0.974 | AP 0.867 | LL 0.2357 | Brier 0.0704
  Fold 2/5
     TRAIN | F1 0.807 | P 0.846 | R 0.771 | AUC 0.981 | AP 0.887 | LL 0.2199 | Brier 0.0658
       VAL | F1 0.787 | P 0.834 | R 0.745 | AUC 0.975 | AP 0.865 | LL 0.2671 | Brier 0.0822
  Fold 3/5
     TRAIN | F1 0.811 | P 0.858 | R 0.769 | AUC 0.981 | AP 0.889 | LL 0.1993 | Brier 0.0585
       VAL | F1 0.817 | P 0.848 | R 0.789 | AUC 0.980 | AP 0.889 | LL 0.2330 | Brier 0.0701
  Fold 4/5
     TRAIN | F1 0.824 | P 0.856 | R 0.794 | AUC 0.983 | AP 0.902 | LL 0.1958 | Brier 0.0581
       VAL | F1 0.795 | P 0.831 | R 0.762 | AUC 0.976 | AP 0.869 | LL 0.2518 | Brier 0.0768
  Fold 5/5
     TRAIN | F1 0.821 | P 0.850 | R 0.795 | AUC 0.983 | AP 0.902 | LL 0.1947 | Brier 0.0574
       VAL | F1 0.811 | P 0.833 | R 0.790 | AUC 0.976 | AP 0.872 | LL 0.2433 | Brier 0.0739
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.814 | P 0.881 | R 0.757 | AUC 0.984 | AP 0.902 | LL 0.2204 | Brier 0.0639
  Saved: /content/outcomes/ibm/ibm_gatv2_hybrid_diagnostics.png

############################################################
# GATv2 | intra_group
############################################################
  Fold 1/5
  [intra_group] nodes=211,649 edges=223,583 deg(min/med/mean/max)=(1,1.0,1.1,20)
  [intra_group] nodes=51,829 edges=63,675 deg(min/med/mean/max)=(1,1.0,1.2,18)
     TRAIN | F1 0.746 | P 0.760 | R 0.732 | AUC 0.956 | AP 0.801 | LL 0.2724 | Brier 0.0732
       VAL | F1 0.745 | P 0.755 | R 0.736 | AUC 0.954 | AP 0.806 | LL 0.2758 | Brier 0.0736
  Fold 2/5
     TRAIN | F1 0.743 | P 0.729 | R 0.757 | AUC 0.959 | AP 0.776 | LL 0.2576 | Brier 0.0668
       VAL | F1 0.736 | P 0.723 | R 0.750 | AUC 0.951 | AP 0.756 | LL 0.2728 | Brier 0.0716
  Fold 3/5
     TRAIN | F1 0.755 | P 0.746 | R 0.764 | AUC 0.957 | AP 0.813 | LL 0.2567 | Brier 0.0684
       VAL | F1 0.767 | P 0.753 | R 0.781 | AUC 0.959 | AP 0.827 | LL 0.2492 | Brier 0.0660
  Fold 4/5
     TRAIN | F1 0.764 | P 0.777 | R 0.752 | AUC 0.962 | AP 0.836 | LL 0.2441 | Brier 0.0657
       VAL | F1 0.735 | P 0.749 | R 0.721 | AUC 0.952 | AP 0.803 | LL 0.2611 | Brier 0.0719
  Fold 5/5
     TRAIN | F1 0.748 | P 0.748 | R 0.748 | AUC 0.959 | AP 0.823 | LL 0.2517 | Brier 0.0677
       VAL | F1 0.742 | P 0.737 | R 0.747 | AUC 0.951 | AP 0.804 | LL 0.2673 | Brier 0.0730
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.770 | P 0.793 | R 0.750 | AUC 0.962 | AP 0.837 | LL 0.2455 | Brier 0.0644
  Saved: /content/outcomes/ibm/ibm_gatv2_intra_group_diagnostics.png

==================================================================================
  Run                              | F1    | P     | R     | AUC   | AP    | Thr
----------------------------------------------------------------------------------
  multi_relation_gatv2             | 0.828 | 0.882 | 0.780 | 0.984 | 0.908 | 0.943
  hybrid_gatv2                     | 0.814 | 0.881 | 0.757 | 0.984 | 0.902 | 0.922
  intra_group_gatv2                | 0.770 | 0.793 | 0.750 | 0.962 | 0.837 | 0.890
==================================================================================
  Saved: /content/outcomes/ibm/ibm_strategy_comparison.png
  Saved: /content/outcomes/ibm/ibm_results_summary.csv

IBM GATv2 baseline done.

---
## Cell 5 — IBM: Sequential LSTM→GAT
~35–55 min on T4 GPU.

In [7]:
import lstm_gat_sequential_model as ibm_lstm_seq
import pickle, os

lstm_seq_results_ibm = {}
for strat in ["multi_relation",
              "hybrid", "intra_group"
              ]:
    save_path = f'/content/drive/MyDrive/lstm_seq_{strat}_result.pkl'
    if os.path.exists(save_path):
        with open(save_path, 'rb') as f:
            lstm_seq_results_ibm[f"{strat}_lstm_gat_seq"] = {'test_metrics': pickle.load(f)}
        print(f"Skipping {strat} — already saved.")
        continue
    lstm_seq_results_ibm[f"{strat}_lstm_gat_seq"] = ibm_lstm_seq.run_pipeline(df_ibm, cfg_ibm, strat)
    with open(save_path, 'wb') as f:
        pickle.dump(lstm_seq_results_ibm[f"{strat}_lstm_gat_seq"]['test_metrics'], f)
    print(f"Saved {strat} to Drive.")

print('\nIBM Sequential LSTM→GAT done.')

############################################################
# LSTM->GAT | multi_relation
############################################################
  Fold 1/5
  [multi_relation] nodes=211,649 edges=916,245 deg(min/med/mean/max)=(1,5.0,4.3,9)
  [multi_relation] nodes=51,829 edges=267,895 deg(min/med/mean/max)=(1,5.0,5.2,9)
     TRAIN | F1 0.876 | P 0.868 | R 0.885 | AUC 0.992 | AP 0.944 | LL 0.1339 | Brier 0.0388
       VAL | F1 0.854 | P 0.865 | R 0.843 | AUC 0.987 | AP 0.922 | LL 0.1414 | Brier 0.0414
  Fold 2/5
     TRAIN | F1 0.877 | P 0.880 | R 0.873 | AUC 0.993 | AP 0.946 | LL 0.1267 | Brier 0.0367
       VAL | F1 0.846 | P 0.877 | R 0.817 | AUC 0.987 | AP 0.922 | LL 0.1281 | Brier 0.0376
  Fold 3/5
     TRAIN | F1 0.876 | P 0.872 | R 0.881 | AUC 0.992 | AP 0.945 | LL 0.1406 | Brier 0.0408
       VAL | F1 0.855 | P 0.861 | R 0.848 | AUC 0.989 | AP 0.929 | LL 0.1596 | Brier 0.0476
  Fold 4/5
     TRAIN | F1 0.893 | P 0.897 | R 0.890 | AUC 0.994 | AP 0.955 | LL 0.1037 | Brier 0.0295
       VAL | F1 0.867 | P 0.893 | R 0.842 | AUC 0.990 | AP 0.937 | LL 0.1178 | Brier 0.0346
  Fold 5/5
     TRAIN | F1 0.870 | P 0.869 | R 0.870 | AUC 0.992 | AP 0.940 | LL 0.1477 | Brier 0.0436
       VAL | F1 0.848 | P 0.852 | R 0.845 | AUC 0.987 | AP 0.920 | LL 0.1760 | Brier 0.0526
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.871 | P 0.910 | R 0.836 | AUC 0.991 | AP 0.941 | LL 0.1230 | Brier 0.0352
  Saved: /content/outcomes/ibm/ibm_lstm_gat_seq_multi_relation_diagnostics.png
Saved multi_relation to Drive.

############################################################
# LSTM->GAT | hybrid
############################################################
  Fold 1/5
  [hybrid] nodes=211,649 edges=2,127,743 deg(min/med/mean/max)=(5,10.0,10.1,53)
  [hybrid] nodes=51,829 edges=561,431 deg(min/med/mean/max)=(5,11.0,10.8,53)
     TRAIN | F1 0.836 | P 0.842 | R 0.830 | AUC 0.986 | AP 0.915 | LL 0.1455 | Brier 0.0420
       VAL | F1 0.823 | P 0.856 | R 0.793 | AUC 0.979 | AP 0.897 | LL 0.1380 | Brier 0.0395
  Fold 2/5
     TRAIN | F1 0.848 | P 0.848 | R 0.848 | AUC 0.988 | AP 0.925 | LL 0.1257 | Brier 0.0361
       VAL | F1 0.824 | P 0.841 | R 0.808 | AUC 0.981 | AP 0.902 | LL 0.1324 | Brier 0.0383
  Fold 3/5
     TRAIN | F1 0.842 | P 0.904 | R 0.788 | AUC 0.988 | AP 0.924 | LL 0.1668 | Brier 0.0492
       VAL | F1 0.837 | P 0.880 | R 0.799 | AUC 0.984 | AP 0.910 | LL 0.1966 | Brier 0.0592
  Fold 4/5
     TRAIN | F1 0.854 | P 0.871 | R 0.837 | AUC 0.988 | AP 0.931 | LL 0.1145 | Brier 0.0323
       VAL | F1 0.830 | P 0.861 | R 0.801 | AUC 0.983 | AP 0.907 | LL 0.1294 | Brier 0.0370
  Fold 5/5
     TRAIN | F1 0.848 | P 0.892 | R 0.808 | AUC 0.989 | AP 0.930 | LL 0.1408 | Brier 0.0410
       VAL | F1 0.833 | P 0.847 | R 0.819 | AUC 0.983 | AP 0.907 | LL 0.1910 | Brier 0.0562
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.843 | P 0.913 | R 0.783 | AUC 0.988 | AP 0.928 | LL 0.1244 | Brier 0.0339
  Saved: /content/outcomes/ibm/ibm_lstm_gat_seq_hybrid_diagnostics.png
Saved hybrid to Drive.

############################################################
# LSTM->GAT | intra_group
############################################################
  Fold 1/5
  [intra_group] nodes=211,649 edges=223,583 deg(min/med/mean/max)=(1,1.0,1.1,20)
  [intra_group] nodes=51,829 edges=63,675 deg(min/med/mean/max)=(1,1.0,1.2,18)
     TRAIN | F1 0.838 | P 0.855 | R 0.821 | AUC 0.983 | AP 0.909 | LL 0.1631 | Brier 0.0453
       VAL | F1 0.838 | P 0.851 | R 0.824 | AUC 0.977 | AP 0.902 | LL 0.1681 | Brier 0.0460
  Fold 2/5
     TRAIN | F1 0.849 | P 0.877 | R 0.824 | AUC 0.985 | AP 0.918 | LL 0.1814 | Brier 0.0514
       VAL | F1 0.842 | P 0.869 | R 0.816 | AUC 0.979 | AP 0.906 | LL 0.2018 | Brier 0.0584
  Fold 3/5
     TRAIN | F1 0.840 | P 0.886 | R 0.799 | AUC 0.984 | AP 0.912 | LL 0.1808 | Brier 0.0512
       VAL | F1 0.849 | P 0.882 | R 0.818 | AUC 0.982 | AP 0.914 | LL 0.1896 | Brier 0.0542
  Fold 4/5
     TRAIN | F1 0.846 | P 0.871 | R 0.822 | AUC 0.985 | AP 0.919 | LL 0.1615 | Brier 0.0459
       VAL | F1 0.832 | P 0.877 | R 0.791 | AUC 0.980 | AP 0.903 | LL 0.1644 | Brier 0.0469
  Fold 5/5
     TRAIN | F1 0.834 | P 0.861 | R 0.808 | AUC 0.985 | AP 0.908 | LL 0.1658 | Brier 0.0468
       VAL | F1 0.834 | P 0.851 | R 0.817 | AUC 0.979 | AP 0.898 | LL 0.1847 | Brier 0.0523
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.853 | P 0.905 | R 0.807 | AUC 0.984 | AP 0.922 | LL 0.1624 | Brier 0.0434
  Saved: /content/outcomes/ibm/ibm_lstm_gat_seq_intra_group_diagnostics.png
Saved intra_group to Drive.

IBM Sequential LSTM→GAT done.

---
## Cell 6 — IBM: Parallel LSTM‖GAT
~45–70 min on T4 GPU.

In [ ]:
import lstm_gat_parallel_model as ibm_lstm_par
import pickle, os

lstm_par_results_ibm = {}
for strat in ["multi_relation",
              "hybrid", "intra_group"]:
    save_path = f'/content/drive/MyDrive/lstm_par_{strat}_result.pkl'
    if os.path.exists(save_path):
        with open(save_path, 'rb') as f:
            lstm_par_results_ibm[f"{strat}_lstm_gat_par"] = {'test_metrics': pickle.load(f)}
        print(f"Skipping {strat} — already saved.")
        continue
    lstm_par_results_ibm[f"{strat}_lstm_gat_par"] = ibm_lstm_par.run_pipeline(df_ibm, cfg_ibm, strat)
    with open(save_path, 'wb') as f:
        pickle.dump(lstm_par_results_ibm[f"{strat}_lstm_gat_par"]['test_metrics'], f)
    print(f"Saved {strat} to Drive.")

print('\nIBM Parallel LSTM‖GAT done.')

############################################################
# LSTM‖GAT (parallel) | multi_relation
############################################################
  Fold 1/5
  [multi_relation] nodes=211,649 edges=916,245 deg(min/med/mean/max)=(1,5.0,4.3,9)
  [multi_relation] nodes=51,829 edges=267,895 deg(min/med/mean/max)=(1,5.0,5.2,9)
     TRAIN | F1 0.811 | P 0.826 | R 0.797 | AUC 0.981 | AP 0.882 | LL 0.2281 | Brier 0.0672
       VAL | F1 0.794 | P 0.813 | R 0.776 | AUC 0.977 | AP 0.869 | LL 0.2398 | Brier 0.0706
  Fold 2/5
     TRAIN | F1 0.800 | P 0.842 | R 0.762 | AUC 0.979 | AP 0.874 | LL 0.2116 | Brier 0.0627
       VAL | F1 0.780 | P 0.829 | R 0.736 | AUC 0.972 | AP 0.855 | LL 0.2439 | Brier 0.0737
  Fold 3/5
     TRAIN | F1 0.793 | P 0.815 | R 0.773 | AUC 0.977 | AP 0.862 | LL 0.2537 | Brier 0.0748
       VAL | F1 0.783 | P 0.799 | R 0.767 | AUC 0.975 | AP 0.857 | LL 0.2893 | Brier 0.0865
  Fold 4/5
     TRAIN | F1 0.810 | P 0.806 | R 0.815 | AUC 0.980 | AP 0.883 | LL 0.2085 | Brier 0.0614
       VAL | F1 0.781 | P 0.796 | R 0.766 | AUC 0.975 | AP 0.854 | LL 0.2180 | Brier 0.0645
  Fold 5/5
     TRAIN | F1 0.817 | P 0.860 | R 0.779 | AUC 0.981 | AP 0.889 | LL 0.2281 | Brier 0.0671
       VAL | F1 0.804 | P 0.827 | R 0.783 | AUC 0.974 | AP 0.863 | LL 0.2845 | Brier 0.0854
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.811 | P 0.870 | R 0.760 | AUC 0.982 | AP 0.892 | LL 0.2320 | Brier 0.0681
  Saved: /content/outcomes/ibm/ibm_lstm_gat_par_multi_relation_diagnostics.png
Saved multi_relation to Drive.
Skipping hybrid — already saved.
Skipping intra_group — already saved.

IBM Parallel LSTM‖GAT done.

---
## Cell 7 — IBM: Homogeneous Account-Level GAT
~5–10 min (far fewer nodes than the transaction-level graphs).

In [ ]:
import account_gat_homogeneous_model as ibm_acct_gat

acct_cfg_ibm = ibm_acct_gat.AccountFraudConfig()
acct_cfg_ibm.OUTCOME_DIR = '/content/outcomes/ibm'

df_accounts_ibm = ibm_acct_gat.build_account_dataframe(df_ibm, acct_cfg_ibm)
acct_results_ibm = ibm_acct_gat.run_all_strategies(df_accounts_ibm, acct_cfg_ibm)
print('\nIBM Homogeneous Account-Level GAT done.')

Aggregating transactions into account-level features...
  1,896 accounts | fraud rate 0.7083

############################################################
# Homogeneous Account GAT | similarity
############################################################
  Fold 1/5
  [similarity] accounts=1,213 edges=16,317 deg(min/med/mean/max)=(9,13.0,13.5,27)
  [similarity] accounts=304 edges=3,936 deg(min/med/mean/max)=(3,12.0,12.9,24)
  Early stop at epoch 80
     TRAIN | F1 0.908 | P 0.898 | R 0.917 | AUC 0.925 | AP 0.964 | LL 0.4698 | Brier 0.1446
       VAL | F1 0.904 | P 0.881 | R 0.928 | AUC 0.908 | AP 0.953 | LL 0.4831 | Brier 0.1507
  Fold 2/5
     TRAIN | F1 0.901 | P 0.888 | R 0.915 | AUC 0.918 | AP 0.961 | LL 0.4372 | Brier 0.1327
       VAL | F1 0.925 | P 0.907 | R 0.942 | AUC 0.938 | AP 0.966 | LL 0.4345 | Brier 0.1299
  Fold 3/5
     TRAIN | F1 0.924 | P 0.895 | R 0.955 | AUC 0.950 | AP 0.975 | LL 0.2748 | Brier 0.0850
       VAL | F1 0.931 | P 0.900 | R 0.964 | AUC 0.941 | AP 0.975 | LL 0.2713 | Brier 0.0835
  Fold 4/5
     TRAIN | F1 0.918 | P 0.893 | R 0.944 | AUC 0.940 | AP 0.972 | LL 0.3403 | Brier 0.1032
       VAL | F1 0.906 | P 0.889 | R 0.923 | AUC 0.903 | AP 0.951 | LL 0.4425 | Brier 0.1374
  Fold 5/5
     TRAIN | F1 0.925 | P 0.928 | R 0.922 | AUC 0.946 | AP 0.974 | LL 0.3051 | Brier 0.0930
       VAL | F1 0.927 | P 0.886 | R 0.972 | AUC 0.929 | AP 0.964 | LL 0.3071 | Brier 0.0925
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.930 | P 0.908 | R 0.953 | AUC 0.912 | AP 0.961 | LL 0.3780 | Brier 0.1142
  Saved: /content/outcomes/ibm/ibm_account_gat_similarity_diagnostics.png

############################################################
# Homogeneous Account GAT | shared_merchant
############################################################
  Fold 1/5
  [shared_merchant] accounts=1,213 edges=1,060,369 deg(min/med/mean/max)=(1,1028.0,874.2,1059)
  [shared_merchant] accounts=304 edges=66,234 deg(min/med/mean/max)=(1,256.0,217.9,269)
     TRAIN | F1 0.897 | P 0.931 | R 0.865 | AUC 0.932 | AP 0.963 | LL 0.4287 | Brier 0.1345
       VAL | F1 0.912 | P 0.857 | R 0.976 | AUC 0.918 | AP 0.954 | LL 0.4273 | Brier 0.1313
  Fold 2/5
     TRAIN | F1 0.918 | P 0.855 | R 0.991 | AUC 0.932 | AP 0.964 | LL 0.3928 | Brier 0.1185
       VAL | F1 0.931 | P 0.890 | R 0.976 | AUC 0.937 | AP 0.959 | LL 0.3987 | Brier 0.1206
  Fold 3/5
     TRAIN | F1 0.894 | P 0.809 | R 0.999 | AUC 0.914 | AP 0.944 | LL 0.4400 | Brier 0.1385
       VAL | F1 0.941 | P 0.889 | R 1.000 | AUC 0.913 | AP 0.956 | LL 0.5530 | Brier 0.1895
  Fold 4/5
     TRAIN | F1 0.929 | P 0.907 | R 0.951 | AUC 0.947 | AP 0.972 | LL 0.4677 | Brier 0.1503
       VAL | F1 0.923 | P 0.904 | R 0.943 | AUC 0.913 | AP 0.945 | LL 0.5713 | Brier 0.1849
  Fold 5/5
     TRAIN | F1 0.798 | P 0.966 | R 0.679 | AUC 0.939 | AP 0.967 | LL 1.6510 | Brier 0.5709
       VAL | F1 0.894 | P 0.808 | R 1.000 | AUC 0.696 | AP 0.808 | LL 1.5725 | Brier 0.5612
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.916 | P 0.908 | R 0.924 | AUC 0.907 | AP 0.947 | LL 0.5670 | Brier 0.1952
  Saved: /content/outcomes/ibm/ibm_account_gat_shared_merchant_diagnostics.png

############################################################
# Homogeneous Account GAT | combined
############################################################
  Fold 1/5
  [combined] accounts=1,213 edges=1,063,443 deg(min/med/mean/max)=(9,1029.0,876.7,1059)
  [combined] accounts=304 edges=67,044 deg(min/med/mean/max)=(9,257.0,220.5,269)
  Early stop at epoch 150
     TRAIN | F1 0.910 | P 0.835 | R 1.000 | AUC 0.864 | AP 0.901 | LL 0.4018 | Brier 0.1225
       VAL | F1 0.900 | P 0.838 | R 0.971 | AUC 0.883 | AP 0.925 | LL 0.6035 | Brier 0.1761
  Fold 2/5
     TRAIN | F1 0.904 | P 0.825 | R 1.000 | AUC 0.918 | AP 0.952 | LL 0.3709 | Brier 0.1107
       VAL | F1 0.943 | P 0.896 | R 0.995 | AUC 0.927 | AP 0.956 | LL 0.5801 | Brier 0.1777
  Fold 3/5
     TRAIN | F1 0.912 | P 0.838 | R 1.000 | AUC 0.899 | AP 0.915 | LL 0.3299 | Brier 0.0973
       VAL | F1 0.935 | P 0.908 | R 0.964 | AUC 0.922 | AP 0.962 | LL 0.4384 | Brier 0.1152
  Fold 4/5
     TRAIN | F1 0.911 | P 0.837 | R 1.000 | AUC 0.929 | AP 0.961 | LL 0.3267 | Brier 0.0950
       VAL | F1 0.901 | P 0.848 | R 0.962 | AUC 0.860 | AP 0.901 | LL 0.6004 | Brier 0.1846
  Fold 5/5
     TRAIN | F1 0.894 | P 0.808 | R 1.000 | AUC 0.854 | AP 0.889 | LL 0.4773 | Brier 0.1528
       VAL | F1 0.907 | P 0.833 | R 0.995 | AUC 0.853 | AP 0.902 | LL 0.6619 | Brier 0.2215
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.911 | P 0.839 | R 0.996 | AUC 0.887 | AP 0.944 | LL 0.4514 | Brier 0.1405
  Saved: /content/outcomes/ibm/ibm_account_gat_combined_diagnostics.png

==================================================================================
  Run                              | F1    | P     | R     | AUC   | AP    | Thr
----------------------------------------------------------------------------------
  similarity_account_gat           | 0.930 | 0.908 | 0.953 | 0.912 | 0.961 | 0.327
  shared_merchant_account_gat      | 0.916 | 0.908 | 0.924 | 0.907 | 0.947 | 0.356
  combined_account_gat             | 0.911 | 0.839 | 0.996 | 0.887 | 0.944 | 0.040
==================================================================================
  Saved: /content/outcomes/ibm/ibm_strategy_comparison.png
  Saved: /content/outcomes/ibm/ibm_results_summary.csv

IBM Homogeneous Account-Level GAT done.

---
## Cell 8 — IBM: combined comparison table

In [ ]:
import pandas as pd

all_results_ibm = {}
all_results_ibm.update(gatv2_results_ibm)
all_results_ibm.update(lstm_seq_results_ibm)
all_results_ibm.update(lstm_par_results_ibm)
all_results_ibm.update(acct_results_ibm)

rows = []
for key, res in all_results_ibm.items():
    m = res['test_metrics']
    rows.append({'run': key, 'model_arch': res.get('model_arch', ''),
                 'graph_strategy': res.get('graph_strategy', ''),
                 'f1': round(m['f1'], 4), 'prec': round(m['prec'], 4), 'rec': round(m['rec'], 4),
                 'auc': round(m['auc'], 4), 'ap': round(m['ap'], 4)})

df_summary_ibm = pd.DataFrame(rows).sort_values(['model_arch', 'f1'], ascending=[True, False])
os.makedirs('/content/outcomes/ibm', exist_ok=True)
df_summary_ibm.to_csv('/content/outcomes/ibm/all_architectures_summary.csv', index=False)
df_summary_ibm

,run,model_arch,graph_strategy,f1,prec,rec,auc,ap
3,multi_relation_lstm_gat_seq,,,0.8743,0.9015,0.8487,0.9914,0.9441
5,intra_group_lstm_gat_seq,,,0.8644,0.9355,0.8033,0.9877,0.9341
4,hybrid_lstm_gat_seq,,,0.8538,0.9228,0.7944,0.9895,0.9335
7,hybrid_lstm_gat_par,,,0.8026,0.8501,0.7601,0.9816,0.8886
8,intra_group_lstm_gat_par,,,0.7524,0.7406,0.7645,0.9555,0.7989
9,similarity_account_gat,account_gat,similarity,0.9298,0.9075,0.9532,0.9119,0.9614
10,shared_merchant_account_gat,account_gat,shared_merchant,0.9162,0.9081,0.9245,0.9074,0.9468
11,combined_account_gat,account_gat,combined,0.9112,0.8394,0.9964,0.8865,0.9442
0,multi_relation_gatv2,gatv2,multi_relation,0.8277,0.8815,0.7801,0.9842,0.9080
1,hybrid_gatv2,gatv2,hybrid,0.8139,0.8806,0.7566,0.9839,0.9021
2,intra_group_gatv2,gatv2,intra_group,0.7705,0.7926,0.7495,0.9622,0.8372
6,multi_relation_lstm_gat_par,lstm_gat_par,multi_relation,0.8113,0.8699,0.7601,0.9818,0.8917

---
# Part B — Sparkov Dataset

## Cell 9 — Load and preprocess
Set `SPARKOV_TRAIN_PATH` / `SPARKOV_TEST_PATH` to your actual
`fraudTrain.csv` / `fraudTest.csv` location before running.
Independent of Part A — safe to run this section on its own.

In [ ]:
import os, sys
import sys

# ibm/ and sparkov/ both have modules with identical filenames
# (config.py, utils.py, gatv2_model.py, etc). Python caches imports by
# name in sys.modules, so re-importing after chdir silently reuses the
# IBM versions unless we evict them first.
for mod in ['config', 'utils', 'gatv2_model', 'lstm_gat_sequential_model',
            'lstm_gat_parallel_model', 'account_gat_homogeneous_model']:
    sys.modules.pop(mod, None)

import os, sys

SPARKOV_TRAIN_PATH = '/content/fraudTrain.csv'  # ← update if needed
SPARKOV_TEST_PATH  = '/content/fraudTest.csv'   # ← update if needed

os.chdir('/content/hybrid-gnn-lstm-fraud/sparkov')
sys.path.insert(0, os.getcwd())

import config as sparkov_cfg
cfg_sparkov = sparkov_cfg.CardFraudConfig()
cfg_sparkov.OUTCOME_DIR = '/content/outcomes/sparkov'

import utils as sparkov_utils
df_sparkov = sparkov_utils.load_and_preprocess(
    train_path=SPARKOV_TRAIN_PATH, test_path=SPARKOV_TEST_PATH, cfg=cfg_sparkov)
print(f'{len(df_sparkov):,} transactions loaded.')

Combined: 1,852,394 transactions
After downsample: 52,394 rows (fraud rate: 0.1842)
Final shape: (52394, 27)
52,394 transactions loaded.

---
## Cell 10 — Sparkov: GATv2 baseline
~20–35 min on T4 GPU.

In [ ]:
import gatv2_model as sparkov_gatv2

gatv2_results_sparkov = sparkov_gatv2.run_all_strategies(df_sparkov, cfg_sparkov)
print('\nSparkov GATv2 baseline done.')

############################################################
# GATv2 | multi_relation
############################################################
  Fold 1/5
  [multi_relation] nodes=33,815 edges=352,233 deg(min/med/mean/max)=(6,11.0,10.4,12)
  [multi_relation] nodes=8,094 edges=81,544 deg(min/med/mean/max)=(5,10.0,10.1,11)
     TRAIN | F1 0.962 | P 0.946 | R 0.979 | AUC 0.999 | AP 0.995 | LL 0.0540 | Brier 0.0151
       VAL | F1 0.928 | P 0.934 | R 0.921 | AUC 0.992 | AP 0.977 | LL 0.0936 | Brier 0.0259
  Fold 2/5
     TRAIN | F1 0.963 | P 0.975 | R 0.951 | AUC 0.999 | AP 0.994 | LL 0.0607 | Brier 0.0169
       VAL | F1 0.929 | P 0.948 | R 0.910 | AUC 0.992 | AP 0.976 | LL 0.1377 | Brier 0.0390
  Fold 3/5
     TRAIN | F1 0.961 | P 0.966 | R 0.957 | AUC 0.999 | AP 0.994 | LL 0.0635 | Brier 0.0175
       VAL | F1 0.918 | P 0.927 | R 0.909 | AUC 0.991 | AP 0.972 | LL 0.1726 | Brier 0.0512
  Fold 4/5
     TRAIN | F1 0.964 | P 0.972 | R 0.955 | AUC 0.999 | AP 0.995 | LL 0.0573 | Brier 0.0158
       VAL | F1 0.924 | P 0.936 | R 0.912 | AUC 0.992 | AP 0.974 | LL 0.1377 | Brier 0.0400
  Fold 5/5
     TRAIN | F1 0.959 | P 0.938 | R 0.981 | AUC 0.999 | AP 0.994 | LL 0.0589 | Brier 0.0163
       VAL | F1 0.920 | P 0.929 | R 0.910 | AUC 0.992 | AP 0.976 | LL 0.0889 | Brier 0.0250
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.909 | P 0.957 | R 0.865 | AUC 0.994 | AP 0.978 | LL 0.1082 | Brier 0.0298
  Saved: /content/outcomes/sparkov/sparkov_gatv2_multi_relation_diagnostics.png

############################################################
# GATv2 | hybrid
############################################################
  Fold 1/5
  [hybrid] nodes=33,815 edges=583,875 deg(min/med/mean/max)=(11,17.0,17.3,28)
  [hybrid] nodes=8,094 edges=137,530 deg(min/med/mean/max)=(12,17.0,17.0,27)
     TRAIN | F1 0.919 | P 0.933 | R 0.905 | AUC 0.992 | AP 0.966 | LL 0.1256 | Brier 0.0333
       VAL | F1 0.865 | P 0.893 | R 0.840 | AUC 0.976 | AP 0.921 | LL 0.1769 | Brier 0.0492
  Fold 2/5
     TRAIN | F1 0.923 | P 0.937 | R 0.909 | AUC 0.993 | AP 0.972 | LL 0.1233 | Brier 0.0334
       VAL | F1 0.885 | P 0.891 | R 0.878 | AUC 0.981 | AP 0.940 | LL 0.2259 | Brier 0.0661
  Fold 3/5
     TRAIN | F1 0.903 | P 0.958 | R 0.854 | AUC 0.993 | AP 0.971 | LL 0.1262 | Brier 0.0343
       VAL | F1 0.862 | P 0.881 | R 0.844 | AUC 0.973 | AP 0.927 | LL 0.3000 | Brier 0.0891
  Fold 4/5
     TRAIN | F1 0.911 | P 0.949 | R 0.876 | AUC 0.992 | AP 0.969 | LL 0.1192 | Brier 0.0324
       VAL | F1 0.863 | P 0.893 | R 0.835 | AUC 0.976 | AP 0.936 | LL 0.2313 | Brier 0.0680
  Fold 5/5
     TRAIN | F1 0.916 | P 0.897 | R 0.937 | AUC 0.992 | AP 0.969 | LL 0.1314 | Brier 0.0352
       VAL | F1 0.863 | P 0.877 | R 0.851 | AUC 0.979 | AP 0.935 | LL 0.1592 | Brier 0.0452
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.862 | P 0.920 | R 0.812 | AUC 0.983 | AP 0.942 | LL 0.1941 | Brier 0.0531
  Saved: /content/outcomes/sparkov/sparkov_gatv2_hybrid_diagnostics.png

############################################################
# GATv2 | intra_group
############################################################
  Fold 1/5
  [intra_group] nodes=33,815 edges=407,381 deg(min/med/mean/max)=(6,12.0,12.0,18)
  [intra_group] nodes=8,094 edges=97,084 deg(min/med/mean/max)=(6,12.0,12.0,17)
     TRAIN | F1 0.945 | P 0.938 | R 0.951 | AUC 0.997 | AP 0.987 | LL 0.0927 | Brier 0.0260
       VAL | F1 0.913 | P 0.931 | R 0.895 | AUC 0.988 | AP 0.969 | LL 0.1138 | Brier 0.0311
  Fold 2/5
     TRAIN | F1 0.941 | P 0.966 | R 0.917 | AUC 0.997 | AP 0.986 | LL 0.0921 | Brier 0.0256
       VAL | F1 0.913 | P 0.942 | R 0.886 | AUC 0.986 | AP 0.967 | LL 0.1475 | Brier 0.0407
  Fold 3/5
     TRAIN | F1 0.932 | P 0.973 | R 0.895 | AUC 0.997 | AP 0.988 | LL 0.1030 | Brier 0.0295
       VAL | F1 0.912 | P 0.924 | R 0.900 | AUC 0.989 | AP 0.968 | LL 0.2279 | Brier 0.0670
  Fold 4/5
     TRAIN | F1 0.943 | P 0.960 | R 0.927 | AUC 0.997 | AP 0.987 | LL 0.0938 | Brier 0.0265
       VAL | F1 0.911 | P 0.928 | R 0.894 | AUC 0.987 | AP 0.966 | LL 0.1844 | Brier 0.0532
  Fold 5/5
     TRAIN | F1 0.936 | P 0.918 | R 0.955 | AUC 0.996 | AP 0.986 | LL 0.0925 | Brier 0.0258
       VAL | F1 0.914 | P 0.903 | R 0.926 | AUC 0.991 | AP 0.973 | LL 0.1110 | Brier 0.0317
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.909 | P 0.943 | R 0.876 | AUC 0.992 | AP 0.971 | LL 0.1350 | Brier 0.0373
  Saved: /content/outcomes/sparkov/sparkov_gatv2_intra_group_diagnostics.png

==================================================================================
  Run                              | F1    | P     | R     | AUC   | AP    | Thr
----------------------------------------------------------------------------------
  multi_relation_gatv2             | 0.909 | 0.957 | 0.865 | 0.994 | 0.978 | 0.875
  hybrid_gatv2                     | 0.862 | 0.920 | 0.812 | 0.983 | 0.942 | 0.818
  intra_group_gatv2                | 0.909 | 0.943 | 0.876 | 0.992 | 0.971 | 0.859
==================================================================================
  Saved: /content/outcomes/sparkov/sparkov_strategy_comparison.png
  Saved: /content/outcomes/sparkov/sparkov_results_summary.csv

Sparkov GATv2 baseline done.

---
## Cell 11 — Sparkov: Sequential LSTM→GAT
~30–50 min on T4 GPU.

In [ ]:
import lstm_gat_sequential_model as sparkov_lstm_seq

lstm_seq_results_sparkov = sparkov_lstm_seq.run_all_strategies(df_sparkov, cfg_sparkov)
print('\nSparkov Sequential LSTM→GAT done.')

############################################################
# LSTM→GAT (sequential) | multi_relation
############################################################
  Fold 1/5
  [multi_relation] nodes=33,815 edges=352,233 deg(min/med/mean/max)=(6,11.0,10.4,12)
  [multi_relation] nodes=8,094 edges=81,544 deg(min/med/mean/max)=(5,10.0,10.1,11)
     TRAIN | F1 0.995 | P 0.992 | R 0.998 | AUC 1.000 | AP 1.000 | LL 0.0130 | Brier 0.0038
       VAL | F1 0.962 | P 0.973 | R 0.950 | AUC 0.997 | AP 0.991 | LL 0.0567 | Brier 0.0130
  Fold 2/5
     TRAIN | F1 0.989 | P 0.978 | R 0.999 | AUC 1.000 | AP 1.000 | LL 0.0165 | Brier 0.0047
       VAL | F1 0.951 | P 0.947 | R 0.955 | AUC 0.997 | AP 0.991 | LL 0.0672 | Brier 0.0159
  Fold 3/5
     TRAIN | F1 0.998 | P 0.998 | R 0.998 | AUC 1.000 | AP 1.000 | LL 0.0078 | Brier 0.0022
       VAL | F1 0.962 | P 0.975 | R 0.950 | AUC 0.998 | AP 0.993 | LL 0.0566 | Brier 0.0149
  Fold 4/5
     TRAIN | F1 0.994 | P 0.989 | R 0.998 | AUC 1.000 | AP 1.000 | LL 0.0131 | Brier 0.0038
       VAL | F1 0.964 | P 0.954 | R 0.975 | AUC 0.999 | AP 0.994 | LL 0.0666 | Brier 0.0186
  Fold 5/5
     TRAIN | F1 0.997 | P 0.995 | R 0.998 | AUC 1.000 | AP 1.000 | LL 0.0100 | Brier 0.0029
       VAL | F1 0.969 | P 0.969 | R 0.970 | AUC 0.999 | AP 0.995 | LL 0.0573 | Brier 0.0135
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.964 | P 0.985 | R 0.943 | AUC 0.999 | AP 0.997 | LL 0.0380 | Brier 0.0114
  Saved: /content/outcomes/sparkov/sparkov_lstm_gat_seq_multi_relation_diagnostics.png

############################################################
# LSTM→GAT (sequential) | hybrid
############################################################
  Fold 1/5
  [hybrid] nodes=33,815 edges=583,875 deg(min/med/mean/max)=(11,17.0,17.3,28)
  [hybrid] nodes=8,094 edges=137,538 deg(min/med/mean/max)=(12,17.0,17.0,27)
     TRAIN | F1 0.994 | P 0.989 | R 0.999 | AUC 1.000 | AP 1.000 | LL 0.0127 | Brier 0.0035
       VAL | F1 0.963 | P 0.971 | R 0.955 | AUC 0.996 | AP 0.991 | LL 0.0560 | Brier 0.0125
  Fold 2/5
     TRAIN | F1 0.992 | P 0.985 | R 0.999 | AUC 1.000 | AP 1.000 | LL 0.0177 | Brier 0.0051
       VAL | F1 0.956 | P 0.967 | R 0.945 | AUC 0.997 | AP 0.991 | LL 0.0600 | Brier 0.0139
  Fold 3/5
     TRAIN | F1 0.995 | P 0.996 | R 0.994 | AUC 1.000 | AP 1.000 | LL 0.0108 | Brier 0.0030
       VAL | F1 0.957 | P 0.957 | R 0.957 | AUC 0.998 | AP 0.992 | LL 0.0660 | Brier 0.0173
  Fold 4/5
     TRAIN | F1 0.994 | P 0.991 | R 0.996 | AUC 1.000 | AP 1.000 | LL 0.0140 | Brier 0.0041
       VAL | F1 0.964 | P 0.963 | R 0.965 | AUC 0.999 | AP 0.994 | LL 0.0547 | Brier 0.0143
  Fold 5/5
     TRAIN | F1 0.996 | P 0.993 | R 0.998 | AUC 1.000 | AP 1.000 | LL 0.0115 | Brier 0.0033
       VAL | F1 0.969 | P 0.974 | R 0.964 | AUC 0.999 | AP 0.995 | LL 0.0432 | Brier 0.0112
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.963 | P 0.983 | R 0.944 | AUC 0.999 | AP 0.996 | LL 0.0371 | Brier 0.0110
  Saved: /content/outcomes/sparkov/sparkov_lstm_gat_seq_hybrid_diagnostics.png

############################################################
# LSTM→GAT (sequential) | intra_group
############################################################
  Fold 1/5
  [intra_group] nodes=33,815 edges=407,381 deg(min/med/mean/max)=(6,12.0,12.0,18)
  [intra_group] nodes=8,094 edges=97,084 deg(min/med/mean/max)=(6,12.0,12.0,17)
     TRAIN | F1 0.994 | P 0.990 | R 0.998 | AUC 1.000 | AP 1.000 | LL 0.0170 | Brier 0.0052
       VAL | F1 0.967 | P 0.977 | R 0.957 | AUC 0.996 | AP 0.992 | LL 0.0525 | Brier 0.0118
  Fold 2/5
     TRAIN | F1 0.990 | P 0.981 | R 0.998 | AUC 1.000 | AP 1.000 | LL 0.0193 | Brier 0.0057
       VAL | F1 0.958 | P 0.961 | R 0.954 | AUC 0.998 | AP 0.992 | LL 0.0585 | Brier 0.0140
  Fold 3/5
     TRAIN | F1 0.994 | P 0.992 | R 0.995 | AUC 1.000 | AP 1.000 | LL 0.0167 | Brier 0.0049
       VAL | F1 0.965 | P 0.967 | R 0.963 | AUC 0.998 | AP 0.994 | LL 0.0611 | Brier 0.0159
  Fold 4/5
     TRAIN | F1 0.995 | P 0.997 | R 0.993 | AUC 1.000 | AP 1.000 | LL 0.0150 | Brier 0.0044
       VAL | F1 0.963 | P 0.966 | R 0.960 | AUC 0.999 | AP 0.994 | LL 0.0696 | Brier 0.0189
  Fold 5/5
     TRAIN | F1 0.996 | P 0.995 | R 0.997 | AUC 1.000 | AP 1.000 | LL 0.0144 | Brier 0.0041
       VAL | F1 0.971 | P 0.980 | R 0.963 | AUC 0.999 | AP 0.997 | LL 0.0431 | Brier 0.0115
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.967 | P 0.980 | R 0.954 | AUC 0.999 | AP 0.997 | LL 0.0383 | Brier 0.0112
  Saved: /content/outcomes/sparkov/sparkov_lstm_gat_seq_intra_group_diagnostics.png

==================================================================================
  Run                              | F1    | P     | R     | AUC   | AP    | Thr
----------------------------------------------------------------------------------
  multi_relation_lstm_gat_seq      | 0.964 | 0.985 | 0.943 | 0.999 | 0.997 | 0.912
  hybrid_lstm_gat_seq              | 0.963 | 0.983 | 0.944 | 0.999 | 0.996 | 0.870
  intra_group_lstm_gat_seq         | 0.967 | 0.980 | 0.954 | 0.999 | 0.997 | 0.880
==================================================================================
  Saved: /content/outcomes/sparkov/sparkov_strategy_comparison.png
  Saved: /content/outcomes/sparkov/sparkov_results_summary.csv

Sparkov Sequential LSTM→GAT done.

---
## Cell 12 — Sparkov: Parallel LSTM‖GAT
~40–65 min on T4 GPU.

In [ ]:
import lstm_gat_parallel_model as sparkov_lstm_par

lstm_par_results_sparkov = sparkov_lstm_par.run_all_strategies(df_sparkov, cfg_sparkov)
print('\nSparkov Parallel LSTM‖GAT done.')

############################################################
# LSTM‖GAT (parallel) | multi_relation
############################################################
  Fold 1/5
  [multi_relation] nodes=33,815 edges=352,233 deg(min/med/mean/max)=(6,11.0,10.4,12)
  [multi_relation] nodes=8,094 edges=81,544 deg(min/med/mean/max)=(5,10.0,10.1,11)
     TRAIN | F1 0.950 | P 0.940 | R 0.961 | AUC 0.997 | AP 0.989 | LL 0.0827 | Brier 0.0226
       VAL | F1 0.918 | P 0.920 | R 0.917 | AUC 0.991 | AP 0.972 | LL 0.1334 | Brier 0.0375
  Fold 2/5
     TRAIN | F1 0.963 | P 0.949 | R 0.978 | AUC 0.999 | AP 0.993 | LL 0.0670 | Brier 0.0187
       VAL | F1 0.925 | P 0.954 | R 0.897 | AUC 0.992 | AP 0.974 | LL 0.0936 | Brier 0.0264
  Fold 3/5
     TRAIN | F1 0.969 | P 0.960 | R 0.978 | AUC 0.999 | AP 0.995 | LL 0.0540 | Brier 0.0150
       VAL | F1 0.932 | P 0.945 | R 0.920 | AUC 0.992 | AP 0.974 | LL 0.0966 | Brier 0.0265
  Fold 4/5
     TRAIN | F1 0.957 | P 0.961 | R 0.953 | AUC 0.998 | AP 0.991 | LL 0.0633 | Brier 0.0170
       VAL | F1 0.930 | P 0.934 | R 0.926 | AUC 0.993 | AP 0.971 | LL 0.1191 | Brier 0.0333
  Fold 5/5
     TRAIN | F1 0.959 | P 0.956 | R 0.963 | AUC 0.998 | AP 0.992 | LL 0.0746 | Brier 0.0204
       VAL | F1 0.939 | P 0.932 | R 0.945 | AUC 0.996 | AP 0.982 | LL 0.1241 | Brier 0.0357
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.915 | P 0.953 | R 0.880 | AUC 0.995 | AP 0.981 | LL 0.0925 | Brier 0.0253
  Saved: /content/outcomes/sparkov/sparkov_lstm_gat_par_multi_relation_diagnostics.png

############################################################
# LSTM‖GAT (parallel) | hybrid
############################################################
  Fold 1/5
  [hybrid] nodes=33,815 edges=583,875 deg(min/med/mean/max)=(11,17.0,17.3,28)
  [hybrid] nodes=8,094 edges=137,524 deg(min/med/mean/max)=(12,17.0,17.0,27)
     TRAIN | F1 0.910 | P 0.959 | R 0.866 | AUC 0.994 | AP 0.972 | LL 0.1021 | Brier 0.0252
       VAL | F1 0.902 | P 0.914 | R 0.891 | AUC 0.983 | AP 0.932 | LL 0.1946 | Brier 0.0522
  Fold 2/5
     TRAIN | F1 0.949 | P 0.927 | R 0.972 | AUC 0.996 | AP 0.979 | LL 0.0857 | Brier 0.0207
       VAL | F1 0.921 | P 0.939 | R 0.904 | AUC 0.987 | AP 0.953 | LL 0.1008 | Brier 0.0252
  Fold 3/5
     TRAIN | F1 0.956 | P 0.946 | R 0.966 | AUC 0.996 | AP 0.979 | LL 0.0742 | Brier 0.0176
       VAL | F1 0.928 | P 0.924 | R 0.932 | AUC 0.988 | AP 0.948 | LL 0.1074 | Brier 0.0262
  Fold 4/5
     TRAIN | F1 0.928 | P 0.966 | R 0.893 | AUC 0.995 | AP 0.975 | LL 0.0840 | Brier 0.0200
       VAL | F1 0.918 | P 0.910 | R 0.926 | AUC 0.989 | AP 0.960 | LL 0.2049 | Brier 0.0580
  Fold 5/5
     TRAIN | F1 0.936 | P 0.944 | R 0.929 | AUC 0.995 | AP 0.971 | LL 0.1122 | Brier 0.0288
       VAL | F1 0.932 | P 0.915 | R 0.949 | AUC 0.992 | AP 0.956 | LL 0.1601 | Brier 0.0439
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.904 | P 0.958 | R 0.855 | AUC 0.993 | AP 0.969 | LL 0.1134 | Brier 0.0286
  Saved: /content/outcomes/sparkov/sparkov_lstm_gat_par_hybrid_diagnostics.png

############################################################
# LSTM‖GAT (parallel) | intra_group
############################################################
  Fold 1/5
  [intra_group] nodes=33,815 edges=407,381 deg(min/med/mean/max)=(6,12.0,12.0,18)
  [intra_group] nodes=8,094 edges=97,084 deg(min/med/mean/max)=(6,12.0,12.0,17)
     TRAIN | F1 0.952 | P 0.953 | R 0.951 | AUC 0.998 | AP 0.989 | LL 0.0857 | Brier 0.0239
       VAL | F1 0.929 | P 0.929 | R 0.929 | AUC 0.992 | AP 0.972 | LL 0.1110 | Brier 0.0292
  Fold 2/5
     TRAIN | F1 0.955 | P 0.956 | R 0.954 | AUC 0.998 | AP 0.990 | LL 0.0774 | Brier 0.0210
       VAL | F1 0.922 | P 0.936 | R 0.909 | AUC 0.990 | AP 0.967 | LL 0.1245 | Brier 0.0344
  Fold 3/5
     TRAIN | F1 0.958 | P 0.948 | R 0.968 | AUC 0.998 | AP 0.991 | LL 0.0711 | Brier 0.0199
       VAL | F1 0.934 | P 0.919 | R 0.950 | AUC 0.992 | AP 0.971 | LL 0.1078 | Brier 0.0302
  Fold 4/5
     TRAIN | F1 0.950 | P 0.957 | R 0.944 | AUC 0.998 | AP 0.989 | LL 0.0752 | Brier 0.0205
       VAL | F1 0.924 | P 0.929 | R 0.919 | AUC 0.993 | AP 0.975 | LL 0.1172 | Brier 0.0334
  Fold 5/5
     TRAIN | F1 0.953 | P 0.958 | R 0.949 | AUC 0.998 | AP 0.991 | LL 0.0936 | Brier 0.0266
       VAL | F1 0.942 | P 0.946 | R 0.938 | AUC 0.995 | AP 0.980 | LL 0.1076 | Brier 0.0301
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.928 | P 0.950 | R 0.906 | AUC 0.994 | AP 0.979 | LL 0.0963 | Brier 0.0267
  Saved: /content/outcomes/sparkov/sparkov_lstm_gat_par_intra_group_diagnostics.png

==================================================================================
  Run                              | F1    | P     | R     | AUC   | AP    | Thr
----------------------------------------------------------------------------------
  multi_relation_lstm_gat_par      | 0.915 | 0.953 | 0.880 | 0.995 | 0.981 | 0.872
  hybrid_lstm_gat_par              | 0.904 | 0.958 | 0.855 | 0.993 | 0.969 | 0.864
  intra_group_lstm_gat_par         | 0.928 | 0.950 | 0.906 | 0.994 | 0.979 | 0.874
==================================================================================
  Saved: /content/outcomes/sparkov/sparkov_strategy_comparison.png
  Saved: /content/outcomes/sparkov/sparkov_results_summary.csv

Sparkov Parallel LSTM‖GAT done.

---
## Cell 13 — Sparkov: Homogeneous Account-Level GAT
~5–10 min.

In [ ]:
import account_gat_homogeneous_model as sparkov_acct_gat

acct_cfg_sparkov = sparkov_acct_gat.CardAccountConfig()
acct_cfg_sparkov.OUTCOME_DIR = '/content/outcomes/sparkov'

df_accounts_sparkov = sparkov_acct_gat.build_account_dataframe(df_sparkov, acct_cfg_sparkov)
acct_results_sparkov = sparkov_acct_gat.run_all_strategies(df_accounts_sparkov, acct_cfg_sparkov)
print('\nSparkov Homogeneous Account-Level GAT done.')

Aggregating transactions into account-level features...
  999 accounts | fraud rate 0.9770

############################################################
# Homogeneous Account GAT | similarity
############################################################
  Fold 1/5
  [similarity] accounts=639 edges=8,669 deg(min/med/mean/max)=(9,13.0,13.6,29)
  [similarity] accounts=160 edges=2,164 deg(min/med/mean/max)=(9,13.0,13.5,26)
  Early stop at epoch 135
     TRAIN | F1 0.956 | P 1.000 | R 0.916 | AUC 0.992 | AP 1.000 | LL 0.2108 | Brier 0.0654
       VAL | F1 0.991 | P 0.981 | R 1.000 | AUC 0.932 | AP 0.999 | LL 0.0683 | Brier 0.0173
  Fold 2/5
     TRAIN | F1 0.961 | P 0.991 | R 0.933 | AUC 0.911 | AP 0.997 | LL 0.5048 | Brier 0.1713
       VAL | F1 0.994 | P 0.987 | R 1.000 | AUC 0.744 | AP 0.991 | LL 0.4390 | Brier 0.1395
  Fold 3/5
     TRAIN | F1 0.983 | P 0.985 | R 0.981 | AUC 0.925 | AP 0.998 | LL 0.4739 | Brier 0.1611
       VAL | F1 0.994 | P 0.988 | R 1.000 | AUC 0.930 | AP 0.999 | LL 0.3917 | Brier 0.1314
  Fold 4/5
     TRAIN | F1 0.994 | P 0.992 | R 0.997 | AUC 0.997 | AP 1.000 | LL 0.1248 | Brier 0.0359
       VAL | F1 0.981 | P 0.963 | R 1.000 | AUC 0.794 | AP 0.991 | LL 0.3530 | Brier 0.0832
  Fold 5/5
     TRAIN | F1 0.963 | P 0.997 | R 0.931 | AUC 0.960 | AP 0.999 | LL 0.3441 | Brier 0.1127
       VAL | F1 0.987 | P 0.975 | R 1.000 | AUC 0.896 | AP 0.996 | LL 0.1990 | Brier 0.0532
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.992 | P 0.985 | R 1.000 | AUC 0.986 | AP 1.000 | LL 0.1929 | Brier 0.0473
  Saved: /content/outcomes/sparkov/sparkov_account_gat_similarity_diagnostics.png

############################################################
# Homogeneous Account GAT | shared_merchant
############################################################
  Fold 1/5
  [shared_merchant] accounts=639 edges=295,429 deg(min/med/mean/max)=(46,508.0,462.3,615)
  [shared_merchant] accounts=160 edges=18,904 deg(min/med/mean/max)=(17,128.0,118.2,155)
     TRAIN | F1 0.998 | P 0.998 | R 0.997 | AUC 0.982 | AP 0.999 | LL 0.1625 | Brier 0.0354
       VAL | F1 0.997 | P 0.994 | R 1.000 | AUC 0.985 | AP 1.000 | LL 0.2319 | Brier 0.0579
  Fold 2/5
     TRAIN | F1 0.988 | P 0.976 | R 1.000 | AUC 0.977 | AP 0.999 | LL 0.4995 | Brier 0.1556
       VAL | F1 0.994 | P 0.987 | R 1.000 | AUC 0.958 | AP 0.999 | LL 1.0566 | Brier 0.3464
  Fold 3/5
     TRAIN | F1 0.988 | P 0.978 | R 0.998 | AUC 0.943 | AP 0.997 | LL 0.6082 | Brier 0.2077
       VAL | F1 0.997 | P 0.994 | R 1.000 | AUC 0.997 | AP 1.000 | LL 0.6865 | Brier 0.2466
  Fold 4/5
     TRAIN | F1 0.000 | P 0.000 | R 0.000 | AUC 0.659 | AP 0.988 | LL 0.6795 | Brier 0.2432
       VAL | F1 0.981 | P 0.963 | R 1.000 | AUC 0.547 | AP 0.973 | LL 0.6712 | Brier 0.2390
  Fold 5/5
     TRAIN | F1 0.960 | P 0.998 | R 0.925 | AUC 0.955 | AP 0.998 | LL 0.1940 | Brier 0.0425
       VAL | F1 1.000 | P 1.000 | R 1.000 | AUC 1.000 | AP 1.000 | LL 0.1196 | Brier 0.0198
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.992 | P 0.985 | R 1.000 | AUC 0.995 | AP 1.000 | LL 0.5201 | Brier 0.1664
  Saved: /content/outcomes/sparkov/sparkov_account_gat_shared_merchant_diagnostics.png

############################################################
# Homogeneous Account GAT | combined
############################################################
  Fold 1/5
  [combined] accounts=639 edges=297,575 deg(min/med/mean/max)=(55,510.0,465.7,615)
  [combined] accounts=160 edges=19,400 deg(min/med/mean/max)=(26,131.0,121.2,155)
  Early stop at epoch 180
     TRAIN | F1 0.919 | P 0.998 | R 0.852 | AUC 0.930 | AP 0.998 | LL 0.4585 | Brier 0.1467
       VAL | F1 0.997 | P 0.994 | R 1.000 | AUC 0.983 | AP 1.000 | LL 0.5046 | Brier 0.1574
  Fold 2/5
     TRAIN | F1 0.994 | P 0.987 | R 1.000 | AUC 0.997 | AP 1.000 | LL 0.2861 | Brier 0.0903
       VAL | F1 0.997 | P 0.994 | R 1.000 | AUC 0.984 | AP 1.000 | LL 0.8190 | Brier 0.2485
  Fold 3/5
     TRAIN | F1 0.991 | P 0.987 | R 0.995 | AUC 0.986 | AP 1.000 | LL 0.3695 | Brier 0.1151
       VAL | F1 0.997 | P 0.994 | R 1.000 | AUC 0.997 | AP 1.000 | LL 0.4701 | Brier 0.1529
  Fold 4/5
     TRAIN | F1 0.968 | P 0.992 | R 0.946 | AUC 0.939 | AP 0.999 | LL 0.4977 | Brier 0.1679
       VAL | F1 0.981 | P 0.963 | R 1.000 | AUC 0.872 | AP 0.994 | LL 0.3883 | Brier 0.1133
  Fold 5/5
     TRAIN | F1 0.956 | P 0.998 | R 0.917 | AUC 0.970 | AP 0.999 | LL 0.2448 | Brier 0.0605
       VAL | F1 1.000 | P 1.000 | R 1.000 | AUC 1.000 | AP 1.000 | LL 0.1138 | Brier 0.0166
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.992 | P 0.985 | R 1.000 | AUC 0.995 | AP 1.000 | LL 0.4781 | Brier 0.1524
  Saved: /content/outcomes/sparkov/sparkov_account_gat_combined_diagnostics.png

==================================================================================
  Run                              | F1    | P     | R     | AUC   | AP    | Thr
----------------------------------------------------------------------------------
  similarity_account_gat           | 0.992 | 0.985 | 1.000 | 0.986 | 1.000 | 0.010
  shared_merchant_account_gat      | 0.992 | 0.985 | 1.000 | 0.995 | 1.000 | 0.038
  combined_account_gat             | 0.992 | 0.985 | 1.000 | 0.995 | 1.000 | 0.013
==================================================================================
  Saved: /content/outcomes/sparkov/sparkov_strategy_comparison.png
  Saved: /content/outcomes/sparkov/sparkov_results_summary.csv

Sparkov Homogeneous Account-Level GAT done.

---
## Cell 14 — Sparkov: combined comparison table

In [ ]:
all_results_sparkov = {}
all_results_sparkov.update(gatv2_results_sparkov)
all_results_sparkov.update(lstm_seq_results_sparkov)
all_results_sparkov.update(lstm_par_results_sparkov)
all_results_sparkov.update(acct_results_sparkov)

rows = []
for key, res in all_results_sparkov.items():
    m = res['test_metrics']
    rows.append({'run': key, 'model_arch': res.get('model_arch', ''),
                 'graph_strategy': res.get('graph_strategy', ''),
                 'f1': round(m['f1'], 4), 'prec': round(m['prec'], 4), 'rec': round(m['rec'], 4),
                 'auc': round(m['auc'], 4), 'ap': round(m['ap'], 4)})

df_summary_sparkov = pd.DataFrame(rows).sort_values(['model_arch', 'f1'], ascending=[True, False])
os.makedirs('/content/outcomes/sparkov', exist_ok=True)
df_summary_sparkov.to_csv('/content/outcomes/sparkov/all_architectures_summary.csv', index=False)
df_summary_sparkov

,run,model_arch,graph_strategy,f1,prec,rec,auc,ap
9,similarity_account_gat,account_gat,similarity,0.9924,0.9850,1.0000,0.9865,0.9998
10,shared_merchant_account_gat,account_gat,shared_merchant,0.9924,0.9850,1.0000,0.9949,0.9999
11,combined_account_gat,account_gat,combined,0.9924,0.9850,1.0000,0.9949,0.9999
0,multi_relation_gatv2,gatv2,multi_relation,0.9088,0.9569,0.8653,0.9943,0.9782
2,intra_group_gatv2,gatv2,intra_group,0.9086,0.9434,0.8762,0.9918,0.9714
1,hybrid_gatv2,gatv2,hybrid,0.8624,0.9199,0.8118,0.9825,0.9418
8,intra_group_lstm_gat_par,lstm_gat_par,intra_group,0.9276,0.9499,0.9064,0.9945,0.9794
6,multi_relation_lstm_gat_par,lstm_gat_par,multi_relation,0.9151,0.9527,0.8804,0.9952,0.9806
7,hybrid_lstm_gat_par,lstm_gat_par,hybrid,0.9038,0.9581,0.8554,0.9926,0.9688
5,intra_group_lstm_gat_seq,lstm_gat_seq,intra_group,0.9668,0.9797,0.9542,0.9993,0.9968
3,multi_relation_lstm_gat_seq,lstm_gat_seq,multi_relation,0.9636,0.9853,0.9428,0.9992,0.9967
4,hybrid_lstm_gat_seq,lstm_gat_seq,hybrid,0.9634,0.9832,0.9444,0.9991,0.9963

---
## Cell 15 — Download everything

In [ ]:
!cd /content/outcomes && zip -qr /content/outcomes.zip .
from google.colab import files
files.download('/content/outcomes.zip')