# Hybrid LSTM+GAT Fraud Detection — IBM & Sparkov
Standalone companion to *Isolating Graph Topology from Model Architecture in
GNN-Based Fraud Detection* (Amiri & Jaf, University of Sunderland, 2026).
Extends the fixed-architecture, variable-topology framework with three
architecture variants per dataset, holding topology fixed and varying
architecture instead — the inverse experiment.

| File | Architecture | Node granularity |
|---|---|---|
| `<dataset>/lstm_gat_sequential_model.py` | LSTM → GAT pipeline | Transaction |
| `<dataset>/lstm_gat_parallel_model.py` | LSTM ‖ GAT, cross-attention fusion | Transaction |
| `<dataset>/account_gat_homogeneous_model.py` | Unchanged GATv2, new topology | Account |

Run the **IBM** section, the **Sparkov** section, or both — they're
independent and don't share state.

---
### Before you start
1. **Runtime → Change runtime type → T4 GPU** (free tier)
2. Update `REPO_URL` in Cell 2
3. Skip whichever dataset section you don't need

---
## Cell 1 — Install dependencies

In [1]:
import subprocess, sys
import torch

torch_version = torch.__version__.split('+')[0]
cuda_version  = 'cu' + torch.version.cuda.replace('.', '') if torch.cuda.is_available() else 'cpu'
print(f'PyTorch {torch_version}  |  CUDA: {cuda_version}')

subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'torch_geometric'], check=True)
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q',
                'scikit-learn', 'pandas', 'matplotlib', 'pyarrow', 'faiss-cpu'], check=True)
print('Done.')

PyTorch 2.11.0  |  CUDA: cu128
Done.

---
## Cell 2 — Clone this repo

In [2]:
import os

REPO_URL = 'https://github.com/Roya62/hybrid-gnn-lstm-fraud'  # ← update

if not os.path.isdir('/content/hybrid-gnn-lstm-fraud'):
    !git clone -q {REPO_URL} /content/hybrid-gnn-lstm-fraud

os.makedirs('/content/outcomes', exist_ok=True)
print('Repo ready at /content/hybrid-gnn-lstm-fraud')

Repo ready at /content/hybrid-gnn-lstm-fraud

---
## Cell 2b — (Optional) Mount Google Drive
Only needed if your dataset files live in Drive.

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

---
# Part A — IBM Dataset

## Cell 3 — Load and preprocess
Set `IBM_DATA_PATH` to your actual `reduced_dataset.parquet` (or
equivalent) location before running.

In [4]:
import os, sys
import sys

for mod in ['config', 'utils', 'gatv2_model', 'lstm_gat_sequential_model',
            'lstm_gat_parallel_model', 'account_gat_homogeneous_model']:
    sys.modules.pop(mod, None)

import os, sys

IBM_DATA_PATH = '/content/drive/MyDrive/reduced_dataset.parquet'  # ← update

os.chdir('/content/hybrid-gnn-lstm-fraud/ibm')
sys.path.insert(0, os.getcwd())

import config as ibm_cfg
cfg_ibm = ibm_cfg.IBMFraudConfig()
cfg_ibm.OUTCOME_DIR = '/content/outcomes/ibm'

import utils as ibm_utils
df_ibm = ibm_utils.load_and_preprocess(path=IBM_DATA_PATH, cfg=cfg_ibm)
print(f'{len(df_ibm):,} transactions loaded.')

Loaded: 24,386,834 transactions
Downsampled: 29,757 fraud + 297,570 non-fraud
After preprocessing: 327,327 rows | Fraud rate: 0.0909
327,327 transactions loaded.

---
## Cell 4 — IBM: GATv2 baseline (fixed architecture, for comparison)
~25–40 min on T4 GPU (all 3 strategies).

In [5]:
import gatv2_model as ibm_gatv2

gatv2_results_ibm = ibm_gatv2.run_all_strategies(df_ibm, cfg_ibm)
print('\nIBM GATv2 baseline done.')

############################################################
# GATv2 | multi_relation
############################################################
  Fold 1/5
  [multi_relation] nodes=211,649 edges=916,245 deg(min/med/mean/max)=(1,5.0,4.3,9)
  [multi_relation] nodes=51,829 edges=267,895 deg(min/med/mean/max)=(1,5.0,5.2,9)
     TRAIN | F1 0.823 | P 0.837 | R 0.808 | AUC 0.981 | AP 0.888 | LL 0.2263 | Brier 0.0666
       VAL | F1 0.808 | P 0.833 | R 0.784 | AUC 0.977 | AP 0.874 | LL 0.2416 | Brier 0.0715
  Fold 2/5
     TRAIN | F1 0.831 | P 0.844 | R 0.819 | AUC 0.984 | AP 0.905 | LL 0.2188 | Brier 0.0640
       VAL | F1 0.805 | P 0.826 | R 0.784 | AUC 0.978 | AP 0.883 | LL 0.2509 | Brier 0.0748
  Fold 3/5
     TRAIN | F1 0.824 | P 0.841 | R 0.809 | AUC 0.982 | AP 0.894 | LL 0.2241 | Brier 0.0652
       VAL | F1 0.822 | P 0.842 | R 0.803 | AUC 0.982 | AP 0.893 | LL 0.2395 | Brier 0.0712
  Fold 4/5
     TRAIN | F1 0.829 | P 0.852 | R 0.808 | AUC 0.984 | AP 0.900 | LL 0.2115 | Brier 0.0624
       VAL | F1 0.796 | P 0.822 | R 0.770 | AUC 0.979 | AP 0.873 | LL 0.2395 | Brier 0.0712
  Fold 5/5
     TRAIN | F1 0.827 | P 0.846 | R 0.809 | AUC 0.983 | AP 0.901 | LL 0.1992 | Brier 0.0578
       VAL | F1 0.808 | P 0.822 | R 0.795 | AUC 0.977 | AP 0.877 | LL 0.2330 | Brier 0.0691
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.828 | P 0.881 | R 0.781 | AUC 0.984 | AP 0.908 | LL 0.2215 | Brier 0.0647
  Saved: /content/outcomes/ibm/ibm_gatv2_multi_relation_diagnostics.png

############################################################
# GATv2 | hybrid
############################################################
  Fold 1/5
  [hybrid] nodes=211,649 edges=2,127,819 deg(min/med/mean/max)=(5,10.0,10.1,56)
  [hybrid] nodes=51,829 edges=561,335 deg(min/med/mean/max)=(5,11.0,10.8,51)
     TRAIN | F1 0.794 | P 0.824 | R 0.766 | AUC 0.979 | AP 0.872 | LL 0.2045 | Brier 0.0595
       VAL | F1 0.794 | P 0.823 | R 0.767 | AUC 0.974 | AP 0.866 | LL 0.2311 | Brier 0.0686
  Fold 2/5
     TRAIN | F1 0.806 | P 0.832 | R 0.782 | AUC 0.981 | AP 0.887 | LL 0.2174 | Brier 0.0650
       VAL | F1 0.786 | P 0.817 | R 0.758 | AUC 0.975 | AP 0.865 | LL 0.2635 | Brier 0.0810
  Fold 3/5
     TRAIN | F1 0.809 | P 0.864 | R 0.761 | AUC 0.981 | AP 0.888 | LL 0.2032 | Brier 0.0596
       VAL | F1 0.817 | P 0.857 | R 0.780 | AUC 0.980 | AP 0.889 | LL 0.2379 | Brier 0.0716
  Fold 4/5
     TRAIN | F1 0.824 | P 0.859 | R 0.792 | AUC 0.983 | AP 0.902 | LL 0.1952 | Brier 0.0579
       VAL | F1 0.795 | P 0.834 | R 0.760 | AUC 0.976 | AP 0.869 | LL 0.2511 | Brier 0.0767
  Fold 5/5
     TRAIN | F1 0.822 | P 0.836 | R 0.809 | AUC 0.983 | AP 0.902 | LL 0.1932 | Brier 0.0569
       VAL | F1 0.810 | P 0.816 | R 0.804 | AUC 0.976 | AP 0.872 | LL 0.2417 | Brier 0.0733
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.814 | P 0.879 | R 0.758 | AUC 0.984 | AP 0.902 | LL 0.2197 | Brier 0.0636
  Saved: /content/outcomes/ibm/ibm_gatv2_hybrid_diagnostics.png

############################################################
# GATv2 | intra_group
############################################################
  Fold 1/5
  [intra_group] nodes=211,649 edges=223,583 deg(min/med/mean/max)=(1,1.0,1.1,20)
  [intra_group] nodes=51,829 edges=63,675 deg(min/med/mean/max)=(1,1.0,1.2,18)
     TRAIN | F1 0.747 | P 0.735 | R 0.761 | AUC 0.956 | AP 0.801 | LL 0.2727 | Brier 0.0733
       VAL | F1 0.745 | P 0.727 | R 0.764 | AUC 0.954 | AP 0.806 | LL 0.2760 | Brier 0.0737
  Fold 2/5
     TRAIN | F1 0.743 | P 0.730 | R 0.757 | AUC 0.959 | AP 0.776 | LL 0.2594 | Brier 0.0673
       VAL | F1 0.736 | P 0.724 | R 0.749 | AUC 0.951 | AP 0.755 | LL 0.2748 | Brier 0.0722
  Fold 3/5
     TRAIN | F1 0.755 | P 0.746 | R 0.764 | AUC 0.957 | AP 0.813 | LL 0.2556 | Brier 0.0681
       VAL | F1 0.767 | P 0.753 | R 0.781 | AUC 0.959 | AP 0.827 | LL 0.2481 | Brier 0.0658
  Fold 4/5
     TRAIN | F1 0.764 | P 0.777 | R 0.752 | AUC 0.962 | AP 0.836 | LL 0.2445 | Brier 0.0658
       VAL | F1 0.735 | P 0.750 | R 0.721 | AUC 0.952 | AP 0.803 | LL 0.2615 | Brier 0.0720
  Fold 5/5
     TRAIN | F1 0.749 | P 0.752 | R 0.746 | AUC 0.959 | AP 0.823 | LL 0.2509 | Brier 0.0675
       VAL | F1 0.742 | P 0.739 | R 0.745 | AUC 0.951 | AP 0.804 | LL 0.2665 | Brier 0.0727
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.770 | P 0.793 | R 0.749 | AUC 0.962 | AP 0.837 | LL 0.2456 | Brier 0.0645
  Saved: /content/outcomes/ibm/ibm_gatv2_intra_group_diagnostics.png

==================================================================================
  Run                              | F1    | P     | R     | AUC   | AP    | Thr
----------------------------------------------------------------------------------
  multi_relation_gatv2             | 0.828 | 0.881 | 0.781 | 0.984 | 0.908 | 0.943
  hybrid_gatv2                     | 0.814 | 0.879 | 0.758 | 0.984 | 0.902 | 0.921
  intra_group_gatv2                | 0.770 | 0.793 | 0.749 | 0.962 | 0.837 | 0.891
==================================================================================
  Saved: /content/outcomes/ibm/ibm_strategy_comparison.png
  Saved: /content/outcomes/ibm/ibm_results_summary.csv

IBM GATv2 baseline done.

---
## Cell 5 — IBM: Sequential LSTM→GAT
~35–55 min on T4 GPU.

In [6]:
import lstm_gat_sequential_model as ibm_lstm_seq
import pickle, os

lstm_seq_results_ibm = {}
for strat in ["multi_relation",
              "hybrid", "intra_group"
              ]:
    save_path = f'/content/drive/MyDrive/lstm_seq_{strat}_result.pkl'
    if os.path.exists(save_path):
        with open(save_path, 'rb') as f:
            lstm_seq_results_ibm[f"{strat}_lstm_gat_seq"] = {'test_metrics': pickle.load(f)}
        print(f"Skipping {strat} — already saved.")
        continue
    lstm_seq_results_ibm[f"{strat}_lstm_gat_seq"] = ibm_lstm_seq.run_pipeline(df_ibm, cfg_ibm, strat)
    with open(save_path, 'wb') as f:
        pickle.dump(lstm_seq_results_ibm[f"{strat}_lstm_gat_seq"]['test_metrics'], f)
    print(f"Saved {strat} to Drive.")

print('\nIBM Sequential LSTM→GAT done.')

############################################################
# LSTM->GAT | multi_relation
############################################################
  Fold 1/5
  [multi_relation] nodes=211,649 edges=916,245 deg(min/med/mean/max)=(1,5.0,4.3,9)
  [multi_relation] nodes=51,829 edges=267,895 deg(min/med/mean/max)=(1,5.0,5.2,9)
     TRAIN | F1 0.889 | P 0.887 | R 0.890 | AUC 0.993 | AP 0.952 | LL 0.1129 | Brier 0.0312
       VAL | F1 0.880 | P 0.901 | R 0.859 | AUC 0.990 | AP 0.941 | LL 0.1078 | Brier 0.0297
  Fold 2/5
     TRAIN | F1 0.894 | P 0.916 | R 0.873 | AUC 0.994 | AP 0.955 | LL 0.1087 | Brier 0.0304
       VAL | F1 0.876 | P 0.902 | R 0.851 | AUC 0.990 | AP 0.942 | LL 0.1222 | Brier 0.0348
  Fold 3/5
     TRAIN | F1 0.882 | P 0.883 | R 0.882 | AUC 0.993 | AP 0.948 | LL 0.1344 | Brier 0.0374
       VAL | F1 0.876 | P 0.875 | R 0.877 | AUC 0.990 | AP 0.939 | LL 0.1455 | Brier 0.0412
  Fold 4/5
     TRAIN | F1 0.897 | P 0.911 | R 0.882 | AUC 0.994 | AP 0.957 | LL 0.1199 | Brier 0.0329
       VAL | F1 0.876 | P 0.908 | R 0.846 | AUC 0.992 | AP 0.945 | LL 0.1301 | Brier 0.0367
  Fold 5/5
     TRAIN | F1 0.888 | P 0.889 | R 0.887 | AUC 0.993 | AP 0.950 | LL 0.1339 | Brier 0.0378
       VAL | F1 0.872 | P 0.880 | R 0.865 | AUC 0.988 | AP 0.933 | LL 0.1350 | Brier 0.0373
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.893 | P 0.939 | R 0.850 | AUC 0.993 | AP 0.958 | LL 0.1048 | Brier 0.0288
  Saved: /content/outcomes/ibm/ibm_lstm_gat_seq_multi_relation_diagnostics.png
Saved multi_relation to Drive.

############################################################
# LSTM->GAT | hybrid
############################################################
  Fold 1/5
  [hybrid] nodes=211,649 edges=2,127,827 deg(min/med/mean/max)=(5,10.0,10.1,52)
  [hybrid] nodes=51,829 edges=561,383 deg(min/med/mean/max)=(5,11.0,10.8,51)
     TRAIN | F1 0.859 | P 0.876 | R 0.843 | AUC 0.989 | AP 0.934 | LL 0.1117 | Brier 0.0315
       VAL | F1 0.850 | P 0.885 | R 0.817 | AUC 0.985 | AP 0.919 | LL 0.1143 | Brier 0.0320
  Fold 2/5
     TRAIN | F1 0.873 | P 0.892 | R 0.854 | AUC 0.991 | AP 0.943 | LL 0.1221 | Brier 0.0345
       VAL | F1 0.854 | P 0.868 | R 0.841 | AUC 0.987 | AP 0.926 | LL 0.1321 | Brier 0.0372
  Fold 3/5
     TRAIN | F1 0.858 | P 0.885 | R 0.832 | AUC 0.989 | AP 0.932 | LL 0.1336 | Brier 0.0380
       VAL | F1 0.854 | P 0.867 | R 0.841 | AUC 0.986 | AP 0.924 | LL 0.1523 | Brier 0.0442
  Fold 4/5
     TRAIN | F1 0.879 | P 0.900 | R 0.859 | AUC 0.992 | AP 0.946 | LL 0.1160 | Brier 0.0323
       VAL | F1 0.860 | P 0.892 | R 0.830 | AUC 0.988 | AP 0.930 | LL 0.1291 | Brier 0.0364
  Fold 5/5
     TRAIN | F1 0.871 | P 0.877 | R 0.864 | AUC 0.991 | AP 0.942 | LL 0.1264 | Brier 0.0360
       VAL | F1 0.852 | P 0.846 | R 0.858 | AUC 0.985 | AP 0.921 | LL 0.1431 | Brier 0.0397
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.872 | P 0.933 | R 0.818 | AUC 0.991 | AP 0.947 | LL 0.1065 | Brier 0.0286
  Saved: /content/outcomes/ibm/ibm_lstm_gat_seq_hybrid_diagnostics.png
Saved hybrid to Drive.

############################################################
# LSTM->GAT | intra_group
############################################################
  Fold 1/5
  [intra_group] nodes=211,649 edges=223,583 deg(min/med/mean/max)=(1,1.0,1.1,20)
  [intra_group] nodes=51,829 edges=63,675 deg(min/med/mean/max)=(1,1.0,1.2,18)
     TRAIN | F1 0.841 | P 0.875 | R 0.810 | AUC 0.983 | AP 0.913 | LL 0.1721 | Brier 0.0477
       VAL | F1 0.841 | P 0.864 | R 0.820 | AUC 0.978 | AP 0.908 | LL 0.1832 | Brier 0.0506
  Fold 2/5
     TRAIN | F1 0.844 | P 0.870 | R 0.819 | AUC 0.985 | AP 0.916 | LL 0.1704 | Brier 0.0483
       VAL | F1 0.845 | P 0.863 | R 0.828 | AUC 0.981 | AP 0.910 | LL 0.1833 | Brier 0.0526
  Fold 3/5
     TRAIN | F1 0.823 | P 0.854 | R 0.794 | AUC 0.981 | AP 0.897 | LL 0.1947 | Brier 0.0546
       VAL | F1 0.827 | P 0.851 | R 0.804 | AUC 0.977 | AP 0.892 | LL 0.2124 | Brier 0.0611
  Fold 4/5
     TRAIN | F1 0.845 | P 0.876 | R 0.817 | AUC 0.985 | AP 0.917 | LL 0.1516 | Brier 0.0408
       VAL | F1 0.832 | P 0.874 | R 0.793 | AUC 0.980 | AP 0.903 | LL 0.1523 | Brier 0.0413
  Fold 5/5
     TRAIN | F1 0.833 | P 0.889 | R 0.784 | AUC 0.983 | AP 0.908 | LL 0.1752 | Brier 0.0494
       VAL | F1 0.831 | P 0.877 | R 0.789 | AUC 0.974 | AP 0.892 | LL 0.1870 | Brier 0.0523
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.850 | P 0.915 | R 0.793 | AUC 0.983 | AP 0.919 | LL 0.1577 | Brier 0.0416
  Saved: /content/outcomes/ibm/ibm_lstm_gat_seq_intra_group_diagnostics.png
Saved intra_group to Drive.

IBM Sequential LSTM→GAT done.

---
## Cell 6 — IBM: Parallel LSTM‖GAT
~45–70 min on T4 GPU.

In [7]:
import lstm_gat_parallel_model as ibm_lstm_par
import pickle, os

lstm_par_results_ibm = {}
for strat in ["multi_relation",
              "hybrid", "intra_group"]:
    save_path = f'/content/drive/MyDrive/lstm_par_{strat}_result.pkl'
    if os.path.exists(save_path):
        with open(save_path, 'rb') as f:
            lstm_par_results_ibm[f"{strat}_lstm_gat_par"] = {'test_metrics': pickle.load(f)}
        print(f"Skipping {strat} — already saved.")
        continue
    lstm_par_results_ibm[f"{strat}_lstm_gat_par"] = ibm_lstm_par.run_pipeline(df_ibm, cfg_ibm, strat)
    with open(save_path, 'wb') as f:
        pickle.dump(lstm_par_results_ibm[f"{strat}_lstm_gat_par"]['test_metrics'], f)
    print(f"Saved {strat} to Drive.")

print('\nIBM Parallel LSTM‖GAT done.')

############################################################
# LSTM‖GAT (parallel) | multi_relation
############################################################
  Fold 1/5
  [multi_relation] nodes=211,649 edges=916,245 deg(min/med/mean/max)=(1,5.0,4.3,9)
  [multi_relation] nodes=51,829 edges=267,895 deg(min/med/mean/max)=(1,5.0,5.2,9)
     TRAIN | F1 0.819 | P 0.822 | R 0.816 | AUC 0.982 | AP 0.884 | LL 0.2071 | Brier 0.0600
       VAL | F1 0.804 | P 0.815 | R 0.794 | AUC 0.977 | AP 0.868 | LL 0.2122 | Brier 0.0613
  Fold 2/5
     TRAIN | F1 0.820 | P 0.819 | R 0.822 | AUC 0.983 | AP 0.887 | LL 0.2112 | Brier 0.0610
       VAL | F1 0.785 | P 0.771 | R 0.799 | AUC 0.975 | AP 0.856 | LL 0.2648 | Brier 0.0779
  Fold 3/5
     TRAIN | F1 0.808 | P 0.800 | R 0.816 | AUC 0.980 | AP 0.878 | LL 0.2123 | Brier 0.0616
       VAL | F1 0.810 | P 0.814 | R 0.806 | AUC 0.980 | AP 0.879 | LL 0.2101 | Brier 0.0610
  Fold 4/5
     TRAIN | F1 0.823 | P 0.806 | R 0.840 | AUC 0.983 | AP 0.890 | LL 0.1982 | Brier 0.0566
       VAL | F1 0.800 | P 0.796 | R 0.805 | AUC 0.979 | AP 0.866 | LL 0.2139 | Brier 0.0617
  Fold 5/5
     TRAIN | F1 0.819 | P 0.835 | R 0.803 | AUC 0.982 | AP 0.885 | LL 0.2082 | Brier 0.0592
       VAL | F1 0.797 | P 0.793 | R 0.800 | AUC 0.976 | AP 0.859 | LL 0.2430 | Brier 0.0695
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.830 | P 0.861 | R 0.800 | AUC 0.984 | AP 0.903 | LL 0.2038 | Brier 0.0589
  Saved: /content/outcomes/ibm/ibm_lstm_gat_par_multi_relation_diagnostics.png
Saved multi_relation to Drive.

############################################################
# LSTM‖GAT (parallel) | hybrid
############################################################
  Fold 1/5
  [hybrid] nodes=211,649 edges=2,127,777 deg(min/med/mean/max)=(5,10.0,10.1,51)
  [hybrid] nodes=51,829 edges=561,381 deg(min/med/mean/max)=(5,11.0,10.8,52)
     TRAIN | F1 0.788 | P 0.806 | R 0.771 | AUC 0.979 | AP 0.869 | LL 0.2108 | Brier 0.0619
       VAL | F1 0.787 | P 0.802 | R 0.772 | AUC 0.973 | AP 0.860 | LL 0.2279 | Brier 0.0676
  Fold 2/5
     TRAIN | F1 0.806 | P 0.842 | R 0.774 | AUC 0.981 | AP 0.885 | LL 0.1975 | Brier 0.0584
       VAL | F1 0.779 | P 0.806 | R 0.753 | AUC 0.974 | AP 0.857 | LL 0.2606 | Brier 0.0798
  Fold 3/5
     TRAIN | F1 0.797 | P 0.818 | R 0.777 | AUC 0.980 | AP 0.877 | LL 0.1837 | Brier 0.0537
       VAL | F1 0.810 | P 0.835 | R 0.786 | AUC 0.979 | AP 0.877 | LL 0.1911 | Brier 0.0564
  Fold 4/5
     TRAIN | F1 0.814 | P 0.812 | R 0.816 | AUC 0.983 | AP 0.890 | LL 0.1821 | Brier 0.0524
       VAL | F1 0.791 | P 0.795 | R 0.786 | AUC 0.977 | AP 0.865 | LL 0.2074 | Brier 0.0608
  Fold 5/5
     TRAIN | F1 0.805 | P 0.837 | R 0.775 | AUC 0.982 | AP 0.888 | LL 0.1884 | Brier 0.0541
       VAL | F1 0.795 | P 0.807 | R 0.783 | AUC 0.975 | AP 0.862 | LL 0.2313 | Brier 0.0675
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.811 | P 0.872 | R 0.758 | AUC 0.983 | AP 0.899 | LL 0.1921 | Brier 0.0549
  Saved: /content/outcomes/ibm/ibm_lstm_gat_par_hybrid_diagnostics.png
Saved hybrid to Drive.

############################################################
# LSTM‖GAT (parallel) | intra_group
############################################################
  Fold 1/5
  [intra_group] nodes=211,649 edges=223,583 deg(min/med/mean/max)=(1,1.0,1.1,20)
  [intra_group] nodes=51,829 edges=63,675 deg(min/med/mean/max)=(1,1.0,1.2,18)
     TRAIN | F1 0.747 | P 0.757 | R 0.738 | AUC 0.955 | AP 0.806 | LL 0.2714 | Brier 0.0720
       VAL | F1 0.747 | P 0.752 | R 0.741 | AUC 0.953 | AP 0.810 | LL 0.2713 | Brier 0.0714
  Fold 2/5
     TRAIN | F1 0.715 | P 0.670 | R 0.765 | AUC 0.957 | AP 0.784 | LL 0.2709 | Brier 0.0772
       VAL | F1 0.705 | P 0.658 | R 0.760 | AUC 0.947 | AP 0.762 | LL 0.3064 | Brier 0.0897
  Fold 3/5
     TRAIN | F1 0.718 | P 0.710 | R 0.726 | AUC 0.954 | AP 0.768 | LL 0.2776 | Brier 0.0750
       VAL | F1 0.737 | P 0.735 | R 0.739 | AUC 0.957 | AP 0.791 | LL 0.2641 | Brier 0.0712
  Fold 4/5
     TRAIN | F1 0.734 | P 0.685 | R 0.791 | AUC 0.956 | AP 0.792 | LL 0.2668 | Brier 0.0736
       VAL | F1 0.712 | P 0.667 | R 0.763 | AUC 0.948 | AP 0.771 | LL 0.2779 | Brier 0.0765
  Fold 5/5
     TRAIN | F1 0.721 | P 0.660 | R 0.795 | AUC 0.956 | AP 0.791 | LL 0.2720 | Brier 0.0742
       VAL | F1 0.714 | P 0.651 | R 0.791 | AUC 0.948 | AP 0.771 | LL 0.2881 | Brier 0.0791
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.738 | P 0.707 | R 0.772 | AUC 0.959 | AP 0.805 | LL 0.2650 | Brier 0.0702
  Saved: /content/outcomes/ibm/ibm_lstm_gat_par_intra_group_diagnostics.png
Saved intra_group to Drive.

IBM Parallel LSTM‖GAT done.

---
## Cell 7 — IBM: Homogeneous Account-Level GAT
~5–10 min (far fewer nodes than the transaction-level graphs).

In [8]:
import account_gat_homogeneous_model as ibm_acct_gat

acct_cfg_ibm = ibm_acct_gat.AccountFraudConfig()
acct_cfg_ibm.OUTCOME_DIR = '/content/outcomes/ibm'

df_accounts_ibm = ibm_acct_gat.build_account_dataframe(df_ibm, acct_cfg_ibm)
acct_results_ibm = ibm_acct_gat.run_all_strategies(df_accounts_ibm, acct_cfg_ibm)
print('\nIBM Homogeneous Account-Level GAT done.')

Aggregating transactions into account-level features...
  1,896 accounts | fraud rate 0.7083

############################################################
# Homogeneous Account GAT | similarity
############################################################
  Fold 1/5
  [similarity] accounts=1,213 edges=16,317 deg(min/med/mean/max)=(9,13.0,13.5,27)
  [similarity] accounts=304 edges=3,936 deg(min/med/mean/max)=(3,12.0,12.9,24)
  Early stop at epoch 80
     TRAIN | F1 0.907 | P 0.897 | R 0.917 | AUC 0.925 | AP 0.964 | LL 0.4698 | Brier 0.1446
       VAL | F1 0.904 | P 0.881 | R 0.928 | AUC 0.908 | AP 0.953 | LL 0.4831 | Brier 0.1507
  Fold 2/5
     TRAIN | F1 0.901 | P 0.888 | R 0.915 | AUC 0.918 | AP 0.961 | LL 0.4372 | Brier 0.1327
       VAL | F1 0.925 | P 0.907 | R 0.942 | AUC 0.938 | AP 0.966 | LL 0.4344 | Brier 0.1299
  Fold 3/5
     TRAIN | F1 0.923 | P 0.914 | R 0.932 | AUC 0.949 | AP 0.974 | LL 0.2852 | Brier 0.0884
       VAL | F1 0.929 | P 0.925 | R 0.933 | AUC 0.941 | AP 0.975 | LL 0.2795 | Brier 0.0863
  Fold 4/5
     TRAIN | F1 0.918 | P 0.893 | R 0.944 | AUC 0.940 | AP 0.972 | LL 0.3404 | Brier 0.1033
       VAL | F1 0.906 | P 0.889 | R 0.923 | AUC 0.903 | AP 0.951 | LL 0.4426 | Brier 0.1375
  Fold 5/5
     TRAIN | F1 0.925 | P 0.927 | R 0.922 | AUC 0.946 | AP 0.974 | LL 0.3051 | Brier 0.0930
       VAL | F1 0.927 | P 0.886 | R 0.972 | AUC 0.929 | AP 0.964 | LL 0.3071 | Brier 0.0925
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.924 | P 0.907 | R 0.942 | AUC 0.912 | AP 0.962 | LL 0.3799 | Brier 0.1151
  Saved: /content/outcomes/ibm/ibm_account_gat_similarity_diagnostics.png

############################################################
# Homogeneous Account GAT | shared_merchant
############################################################
  Fold 1/5
  [shared_merchant] accounts=1,213 edges=1,060,369 deg(min/med/mean/max)=(1,1028.0,874.2,1059)
  [shared_merchant] accounts=304 edges=66,234 deg(min/med/mean/max)=(1,256.0,217.9,269)
     TRAIN | F1 0.909 | P 0.911 | R 0.907 | AUC 0.932 | AP 0.963 | LL 0.4330 | Brier 0.1362
       VAL | F1 0.912 | P 0.841 | R 0.995 | AUC 0.918 | AP 0.955 | LL 0.4261 | Brier 0.1308
  Fold 2/5
     TRAIN | F1 0.915 | P 0.845 | R 0.998 | AUC 0.933 | AP 0.964 | LL 0.3912 | Brier 0.1185
       VAL | F1 0.932 | P 0.880 | R 0.990 | AUC 0.937 | AP 0.959 | LL 0.3983 | Brier 0.1205
  Fold 3/5
     TRAIN | F1 0.853 | P 0.939 | R 0.782 | AUC 0.925 | AP 0.955 | LL 0.3623 | Brier 0.1074
       VAL | F1 0.944 | P 0.909 | R 0.982 | AUC 0.934 | AP 0.967 | LL 0.3715 | Brier 0.1124
  Fold 4/5
     TRAIN | F1 0.928 | P 0.893 | R 0.965 | AUC 0.945 | AP 0.971 | LL 0.3753 | Brier 0.1174
       VAL | F1 0.923 | P 0.904 | R 0.943 | AUC 0.912 | AP 0.945 | LL 0.4656 | Brier 0.1528
  Fold 5/5
     TRAIN | F1 0.777 | P 0.972 | R 0.647 | AUC 0.939 | AP 0.966 | LL 1.6857 | Brier 0.5762
       VAL | F1 0.899 | P 0.822 | R 0.991 | AUC 0.674 | AP 0.785 | LL 1.6123 | Brier 0.5689
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.903 | P 0.915 | R 0.892 | AUC 0.907 | AP 0.947 | LL 0.5424 | Brier 0.1834
  Saved: /content/outcomes/ibm/ibm_account_gat_shared_merchant_diagnostics.png

############################################################
# Homogeneous Account GAT | combined
############################################################
  Fold 1/5
  [combined] accounts=1,213 edges=1,063,443 deg(min/med/mean/max)=(9,1029.0,876.7,1059)
  [combined] accounts=304 edges=67,044 deg(min/med/mean/max)=(9,257.0,220.5,269)
  Early stop at epoch 150
     TRAIN | F1 0.911 | P 0.836 | R 1.000 | AUC 0.863 | AP 0.900 | LL 0.4024 | Brier 0.1226
       VAL | F1 0.900 | P 0.838 | R 0.971 | AUC 0.882 | AP 0.923 | LL 0.6044 | Brier 0.1763
  Fold 2/5
     TRAIN | F1 0.904 | P 0.826 | R 1.000 | AUC 0.916 | AP 0.951 | LL 0.3891 | Brier 0.1178
       VAL | F1 0.943 | P 0.896 | R 0.995 | AUC 0.926 | AP 0.956 | LL 0.6128 | Brier 0.1924
  Fold 3/5
     TRAIN | F1 0.912 | P 0.838 | R 1.000 | AUC 0.898 | AP 0.913 | LL 0.3276 | Brier 0.0967
       VAL | F1 0.935 | P 0.908 | R 0.964 | AUC 0.919 | AP 0.959 | LL 0.4312 | Brier 0.1136
  Fold 4/5
     TRAIN | F1 0.911 | P 0.837 | R 1.000 | AUC 0.929 | AP 0.961 | LL 0.3266 | Brier 0.0950
       VAL | F1 0.901 | P 0.848 | R 0.962 | AUC 0.861 | AP 0.903 | LL 0.6133 | Brier 0.1893
  Fold 5/5
     TRAIN | F1 0.896 | P 0.811 | R 1.000 | AUC 0.853 | AP 0.888 | LL 0.4778 | Brier 0.1530
       VAL | F1 0.906 | P 0.835 | R 0.991 | AUC 0.853 | AP 0.905 | LL 0.6628 | Brier 0.2219
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.911 | P 0.839 | R 0.996 | AUC 0.887 | AP 0.945 | LL 0.4562 | Brier 0.1423
  Saved: /content/outcomes/ibm/ibm_account_gat_combined_diagnostics.png

==================================================================================
  Run                              | F1    | P     | R     | AUC   | AP    | Thr
----------------------------------------------------------------------------------
  similarity_account_gat           | 0.924 | 0.907 | 0.942 | 0.912 | 0.962 | 0.338
  shared_merchant_account_gat      | 0.903 | 0.915 | 0.892 | 0.907 | 0.947 | 0.409
  combined_account_gat             | 0.911 | 0.839 | 0.996 | 0.887 | 0.945 | 0.040
==================================================================================
  Saved: /content/outcomes/ibm/ibm_strategy_comparison.png
  Saved: /content/outcomes/ibm/ibm_results_summary.csv

IBM Homogeneous Account-Level GAT done.

---
## Cell 8 — IBM: combined comparison table

In [9]:
import pandas as pd

all_results_ibm = {}
all_results_ibm.update(gatv2_results_ibm)
all_results_ibm.update(lstm_seq_results_ibm)
all_results_ibm.update(lstm_par_results_ibm)
all_results_ibm.update(acct_results_ibm)

rows = []
for key, res in all_results_ibm.items():
    m = res['test_metrics']
    rows.append({'run': key, 'model_arch': res.get('model_arch', ''),
                 'graph_strategy': res.get('graph_strategy', ''),
                 'f1': round(m['f1'], 4), 'prec': round(m['prec'], 4), 'rec': round(m['rec'], 4),
                 'auc': round(m['auc'], 4), 'ap': round(m['ap'], 4)})

df_summary_ibm = pd.DataFrame(rows).sort_values(['model_arch', 'f1'], ascending=[True, False])
os.makedirs('/content/outcomes/ibm', exist_ok=True)
df_summary_ibm.to_csv('/content/outcomes/ibm/all_architectures_summary.csv', index=False)
df_summary_ibm

,run,model_arch,graph_strategy,f1,prec,rec,auc,ap
9,similarity_account_gat,account_gat,similarity,0.9242,0.9066,0.9424,0.9121,0.9615
11,combined_account_gat,account_gat,combined,0.9112,0.8394,0.9964,0.8868,0.9449
10,shared_merchant_account_gat,account_gat,shared_merchant,0.9035,0.9151,0.8921,0.9073,0.9472
0,multi_relation_gatv2,gatv2,multi_relation,0.8279,0.8809,0.7808,0.9842,0.9080
1,hybrid_gatv2,gatv2,hybrid,0.8139,0.8787,0.7580,0.9839,0.9021
2,intra_group_gatv2,gatv2,intra_group,0.7700,0.7927,0.7486,0.9622,0.8372
6,multi_relation_lstm_gat_par,lstm_gat_par,multi_relation,0.8298,0.8614,0.8004,0.9842,0.9026
7,hybrid_lstm_gat_par,lstm_gat_par,hybrid,0.8109,0.8722,0.7576,0.9834,0.8987
8,intra_group_lstm_gat_par,lstm_gat_par,intra_group,0.7383,0.7073,0.7720,0.9593,0.8052
3,multi_relation_lstm_gat_seq,lstm_gat_seq,multi_relation,0.8926,0.9390,0.8505,0.9933,0.9579
4,hybrid_lstm_gat_seq,lstm_gat_seq,hybrid,0.8719,0.9328,0.8185,0.9914,0.9466
5,intra_group_lstm_gat_seq,lstm_gat_seq,intra_group,0.8498,0.9148,0.7935,0.9826,0.9186

---
# Part B — Sparkov Dataset

## Cell 9 — Load and preprocess
Set `SPARKOV_TRAIN_PATH` / `SPARKOV_TEST_PATH` to your actual
`fraudTrain.csv` / `fraudTest.csv` location before running.
Independent of Part A — safe to run this section on its own.

In [10]:
import os, sys
import sys

# ibm/ and sparkov/ both have modules with identical filenames
# (config.py, utils.py, gatv2_model.py, etc). Python caches imports by
# name in sys.modules, so re-importing after chdir silently reuses the
# IBM versions unless we evict them first.
for mod in ['config', 'utils', 'gatv2_model', 'lstm_gat_sequential_model',
            'lstm_gat_parallel_model', 'account_gat_homogeneous_model']:
    sys.modules.pop(mod, None)

import os, sys

SPARKOV_TRAIN_PATH = '/content/fraudTrain.csv'  # ← update if needed
SPARKOV_TEST_PATH  = '/content/fraudTest.csv'   # ← update if needed

os.chdir('/content/hybrid-gnn-lstm-fraud/sparkov')
sys.path.insert(0, os.getcwd())

import config as sparkov_cfg
cfg_sparkov = sparkov_cfg.CardFraudConfig()
cfg_sparkov.OUTCOME_DIR = '/content/outcomes/sparkov'

import utils as sparkov_utils
df_sparkov = sparkov_utils.load_and_preprocess(
    train_path=SPARKOV_TRAIN_PATH, test_path=SPARKOV_TEST_PATH, cfg=cfg_sparkov)
print(f'{len(df_sparkov):,} transactions loaded.')

Combined: 1,852,394 transactions
After downsample: 52,394 rows (fraud rate: 0.1842)
Final shape: (52394, 27)
52,394 transactions loaded.

---
## Cell 10 — Sparkov: GATv2 baseline
~20–35 min on T4 GPU.

In [11]:
import gatv2_model as sparkov_gatv2

gatv2_results_sparkov = sparkov_gatv2.run_all_strategies(df_sparkov, cfg_sparkov)
print('\nSparkov GATv2 baseline done.')

############################################################
# GATv2 | multi_relation
############################################################
  Fold 1/5
  [multi_relation] nodes=33,815 edges=352,233 deg(min/med/mean/max)=(6,11.0,10.4,12)
  [multi_relation] nodes=8,094 edges=81,544 deg(min/med/mean/max)=(5,10.0,10.1,11)
     TRAIN | F1 0.962 | P 0.944 | R 0.980 | AUC 0.999 | AP 0.995 | LL 0.0542 | Brier 0.0151
       VAL | F1 0.928 | P 0.933 | R 0.923 | AUC 0.992 | AP 0.977 | LL 0.0933 | Brier 0.0258
  Fold 2/5
     TRAIN | F1 0.963 | P 0.974 | R 0.953 | AUC 0.999 | AP 0.994 | LL 0.0608 | Brier 0.0169
       VAL | F1 0.929 | P 0.947 | R 0.911 | AUC 0.992 | AP 0.976 | LL 0.1370 | Brier 0.0387
  Fold 3/5
     TRAIN | F1 0.962 | P 0.966 | R 0.957 | AUC 0.999 | AP 0.994 | LL 0.0635 | Brier 0.0175
       VAL | F1 0.917 | P 0.926 | R 0.909 | AUC 0.991 | AP 0.972 | LL 0.1730 | Brier 0.0513
  Fold 4/5
     TRAIN | F1 0.963 | P 0.972 | R 0.955 | AUC 0.999 | AP 0.995 | LL 0.0574 | Brier 0.0158
       VAL | F1 0.924 | P 0.938 | R 0.911 | AUC 0.992 | AP 0.974 | LL 0.1380 | Brier 0.0400
  Fold 5/5
     TRAIN | F1 0.958 | P 0.935 | R 0.982 | AUC 0.999 | AP 0.994 | LL 0.0588 | Brier 0.0163
       VAL | F1 0.919 | P 0.927 | R 0.912 | AUC 0.992 | AP 0.975 | LL 0.0890 | Brier 0.0250
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.909 | P 0.957 | R 0.865 | AUC 0.994 | AP 0.978 | LL 0.1082 | Brier 0.0298
  Saved: /content/outcomes/sparkov/sparkov_gatv2_multi_relation_diagnostics.png

############################################################
# GATv2 | hybrid
############################################################
  Fold 1/5
  [hybrid] nodes=33,815 edges=583,875 deg(min/med/mean/max)=(11,17.0,17.3,28)
  [hybrid] nodes=8,094 edges=137,516 deg(min/med/mean/max)=(12,17.0,17.0,27)
     TRAIN | F1 0.919 | P 0.929 | R 0.909 | AUC 0.992 | AP 0.966 | LL 0.1266 | Brier 0.0336
       VAL | F1 0.865 | P 0.882 | R 0.849 | AUC 0.976 | AP 0.921 | LL 0.1822 | Brier 0.0509
  Fold 2/5
     TRAIN | F1 0.921 | P 0.944 | R 0.899 | AUC 0.993 | AP 0.972 | LL 0.1293 | Brier 0.0353
       VAL | F1 0.885 | P 0.902 | R 0.869 | AUC 0.981 | AP 0.940 | LL 0.2389 | Brier 0.0703
  Fold 3/5
     TRAIN | F1 0.903 | P 0.958 | R 0.853 | AUC 0.993 | AP 0.972 | LL 0.1260 | Brier 0.0343
       VAL | F1 0.862 | P 0.882 | R 0.844 | AUC 0.973 | AP 0.926 | LL 0.2969 | Brier 0.0880
  Fold 4/5
     TRAIN | F1 0.914 | P 0.943 | R 0.886 | AUC 0.992 | AP 0.968 | LL 0.1164 | Brier 0.0313
       VAL | F1 0.863 | P 0.877 | R 0.848 | AUC 0.976 | AP 0.934 | LL 0.2274 | Brier 0.0664
  Fold 5/5
     TRAIN | F1 0.918 | P 0.894 | R 0.942 | AUC 0.993 | AP 0.971 | LL 0.1272 | Brier 0.0340
       VAL | F1 0.864 | P 0.885 | R 0.844 | AUC 0.979 | AP 0.936 | LL 0.1493 | Brier 0.0422
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.862 | P 0.912 | R 0.817 | AUC 0.983 | AP 0.942 | LL 0.1939 | Brier 0.0530
  Saved: /content/outcomes/sparkov/sparkov_gatv2_hybrid_diagnostics.png

############################################################
# GATv2 | intra_group
############################################################
  Fold 1/5
  [intra_group] nodes=33,815 edges=407,381 deg(min/med/mean/max)=(6,12.0,12.0,18)
  [intra_group] nodes=8,094 edges=97,084 deg(min/med/mean/max)=(6,12.0,12.0,17)
     TRAIN | F1 0.945 | P 0.939 | R 0.951 | AUC 0.997 | AP 0.987 | LL 0.0923 | Brier 0.0259
       VAL | F1 0.913 | P 0.931 | R 0.895 | AUC 0.988 | AP 0.969 | LL 0.1135 | Brier 0.0310
  Fold 2/5
     TRAIN | F1 0.941 | P 0.965 | R 0.919 | AUC 0.997 | AP 0.986 | LL 0.0922 | Brier 0.0256
       VAL | F1 0.913 | P 0.941 | R 0.886 | AUC 0.986 | AP 0.967 | LL 0.1474 | Brier 0.0407
  Fold 3/5
     TRAIN | F1 0.936 | P 0.969 | R 0.906 | AUC 0.997 | AP 0.988 | LL 0.1027 | Brier 0.0295
       VAL | F1 0.912 | P 0.914 | R 0.910 | AUC 0.989 | AP 0.968 | LL 0.2273 | Brier 0.0668
  Fold 4/5
     TRAIN | F1 0.943 | P 0.962 | R 0.924 | AUC 0.997 | AP 0.987 | LL 0.0937 | Brier 0.0265
       VAL | F1 0.911 | P 0.931 | R 0.892 | AUC 0.987 | AP 0.966 | LL 0.1843 | Brier 0.0532
  Fold 5/5
     TRAIN | F1 0.936 | P 0.918 | R 0.955 | AUC 0.996 | AP 0.986 | LL 0.0925 | Brier 0.0258
       VAL | F1 0.914 | P 0.903 | R 0.926 | AUC 0.991 | AP 0.973 | LL 0.1110 | Brier 0.0317
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.910 | P 0.943 | R 0.879 | AUC 0.992 | AP 0.971 | LL 0.1349 | Brier 0.0373
  Saved: /content/outcomes/sparkov/sparkov_gatv2_intra_group_diagnostics.png

==================================================================================
  Run                              | F1    | P     | R     | AUC   | AP    | Thr
----------------------------------------------------------------------------------
  multi_relation_gatv2             | 0.909 | 0.957 | 0.865 | 0.994 | 0.978 | 0.874
  hybrid_gatv2                     | 0.862 | 0.912 | 0.817 | 0.983 | 0.942 | 0.796
  intra_group_gatv2                | 0.910 | 0.943 | 0.879 | 0.992 | 0.971 | 0.857
==================================================================================
  Saved: /content/outcomes/sparkov/sparkov_strategy_comparison.png
  Saved: /content/outcomes/sparkov/sparkov_results_summary.csv

Sparkov GATv2 baseline done.

---
## Cell 11 — Sparkov: Sequential LSTM→GAT
~30–50 min on T4 GPU.

In [12]:
import lstm_gat_sequential_model as sparkov_lstm_seq

lstm_seq_results_sparkov = sparkov_lstm_seq.run_all_strategies(df_sparkov, cfg_sparkov)
print('\nSparkov Sequential LSTM→GAT done.')

############################################################
# LSTM→GAT (sequential) | multi_relation
############################################################
  Fold 1/5
  [multi_relation] nodes=33,815 edges=352,233 deg(min/med/mean/max)=(6,11.0,10.4,12)
  [multi_relation] nodes=8,094 edges=81,544 deg(min/med/mean/max)=(5,10.0,10.1,11)
     TRAIN | F1 0.975 | P 0.992 | R 0.959 | AUC 1.000 | AP 0.998 | LL 0.0375 | Brier 0.0106
       VAL | F1 0.936 | P 0.962 | R 0.911 | AUC 0.994 | AP 0.982 | LL 0.1295 | Brier 0.0374
  Fold 2/5
     TRAIN | F1 0.976 | P 0.986 | R 0.967 | AUC 1.000 | AP 0.998 | LL 0.0352 | Brier 0.0099
       VAL | F1 0.942 | P 0.960 | R 0.925 | AUC 0.994 | AP 0.982 | LL 0.0959 | Brier 0.0270
  Fold 3/5
     TRAIN | F1 0.979 | P 0.983 | R 0.976 | AUC 0.999 | AP 0.998 | LL 0.0389 | Brier 0.0107
       VAL | F1 0.931 | P 0.946 | R 0.917 | AUC 0.993 | AP 0.978 | LL 0.1156 | Brier 0.0329
  Fold 4/5
     TRAIN | F1 0.977 | P 0.986 | R 0.969 | AUC 1.000 | AP 0.998 | LL 0.0313 | Brier 0.0084
       VAL | F1 0.935 | P 0.947 | R 0.924 | AUC 0.995 | AP 0.982 | LL 0.1117 | Brier 0.0321
  Fold 5/5
     TRAIN | F1 0.980 | P 0.980 | R 0.980 | AUC 0.999 | AP 0.998 | LL 0.0403 | Brier 0.0111
       VAL | F1 0.954 | P 0.952 | R 0.957 | AUC 0.997 | AP 0.990 | LL 0.0991 | Brier 0.0285
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.935 | P 0.968 | R 0.905 | AUC 0.997 | AP 0.988 | LL 0.0906 | Brier 0.0254
  Saved: /content/outcomes/sparkov/sparkov_lstm_gat_seq_multi_relation_diagnostics.png

############################################################
# LSTM→GAT (sequential) | hybrid
############################################################
  Fold 1/5
  [hybrid] nodes=33,815 edges=583,875 deg(min/med/mean/max)=(11,17.0,17.3,28)
  [hybrid] nodes=8,094 edges=137,530 deg(min/med/mean/max)=(12,17.0,17.0,27)
     TRAIN | F1 0.951 | P 0.984 | R 0.920 | AUC 0.999 | AP 0.994 | LL 0.0599 | Brier 0.0166
       VAL | F1 0.918 | P 0.934 | R 0.902 | AUC 0.990 | AP 0.970 | LL 0.1691 | Brier 0.0468
  Fold 2/5
     TRAIN | F1 0.962 | P 0.968 | R 0.956 | AUC 0.999 | AP 0.994 | LL 0.0579 | Brier 0.0157
       VAL | F1 0.927 | P 0.939 | R 0.916 | AUC 0.991 | AP 0.973 | LL 0.1305 | Brier 0.0373
  Fold 3/5
     TRAIN | F1 0.956 | P 0.953 | R 0.958 | AUC 0.998 | AP 0.992 | LL 0.0661 | Brier 0.0182
       VAL | F1 0.911 | P 0.924 | R 0.899 | AUC 0.988 | AP 0.965 | LL 0.1191 | Brier 0.0328
  Fold 4/5
     TRAIN | F1 0.955 | P 0.971 | R 0.939 | AUC 0.998 | AP 0.992 | LL 0.0691 | Brier 0.0185
       VAL | F1 0.918 | P 0.925 | R 0.911 | AUC 0.991 | AP 0.972 | LL 0.1527 | Brier 0.0429
  Fold 5/5
     TRAIN | F1 0.958 | P 0.971 | R 0.945 | AUC 0.998 | AP 0.993 | LL 0.0625 | Brier 0.0171
       VAL | F1 0.934 | P 0.936 | R 0.932 | AUC 0.993 | AP 0.977 | LL 0.1365 | Brier 0.0376
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.913 | P 0.962 | R 0.869 | AUC 0.994 | AP 0.979 | LL 0.1151 | Brier 0.0321
  Saved: /content/outcomes/sparkov/sparkov_lstm_gat_seq_hybrid_diagnostics.png

############################################################
# LSTM→GAT (sequential) | intra_group
############################################################
  Fold 1/5
  [intra_group] nodes=33,815 edges=407,381 deg(min/med/mean/max)=(6,12.0,12.0,18)
  [intra_group] nodes=8,094 edges=97,084 deg(min/med/mean/max)=(6,12.0,12.0,17)
     TRAIN | F1 0.971 | P 0.980 | R 0.962 | AUC 0.999 | AP 0.996 | LL 0.0501 | Brier 0.0140
       VAL | F1 0.938 | P 0.946 | R 0.930 | AUC 0.994 | AP 0.982 | LL 0.0980 | Brier 0.0249
  Fold 2/5
     TRAIN | F1 0.972 | P 0.962 | R 0.981 | AUC 0.999 | AP 0.997 | LL 0.0453 | Brier 0.0127
       VAL | F1 0.945 | P 0.941 | R 0.949 | AUC 0.995 | AP 0.984 | LL 0.0889 | Brier 0.0242
  Fold 3/5
     TRAIN | F1 0.970 | P 0.964 | R 0.977 | AUC 0.999 | AP 0.996 | LL 0.0505 | Brier 0.0141
       VAL | F1 0.938 | P 0.943 | R 0.933 | AUC 0.994 | AP 0.981 | LL 0.0878 | Brier 0.0244
  Fold 4/5
     TRAIN | F1 0.969 | P 0.983 | R 0.956 | AUC 0.999 | AP 0.995 | LL 0.0472 | Brier 0.0127
       VAL | F1 0.935 | P 0.956 | R 0.915 | AUC 0.995 | AP 0.982 | LL 0.0982 | Brier 0.0274
  Fold 5/5
     TRAIN | F1 0.968 | P 0.983 | R 0.954 | AUC 0.999 | AP 0.996 | LL 0.0437 | Brier 0.0122
       VAL | F1 0.954 | P 0.963 | R 0.944 | AUC 0.997 | AP 0.989 | LL 0.0811 | Brier 0.0225
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.944 | P 0.958 | R 0.930 | AUC 0.997 | AP 0.989 | LL 0.0734 | Brier 0.0208
  Saved: /content/outcomes/sparkov/sparkov_lstm_gat_seq_intra_group_diagnostics.png

==================================================================================
  Run                              | F1    | P     | R     | AUC   | AP    | Thr
----------------------------------------------------------------------------------
  multi_relation_lstm_gat_seq      | 0.935 | 0.968 | 0.905 | 0.997 | 0.988 | 0.922
  hybrid_lstm_gat_seq              | 0.913 | 0.962 | 0.869 | 0.994 | 0.979 | 0.919
  intra_group_lstm_gat_seq         | 0.944 | 0.958 | 0.930 | 0.997 | 0.989 | 0.838
==================================================================================
  Saved: /content/outcomes/sparkov/sparkov_strategy_comparison.png
  Saved: /content/outcomes/sparkov/sparkov_results_summary.csv

Sparkov Sequential LSTM→GAT done.

---
## Cell 12 — Sparkov: Parallel LSTM‖GAT
~40–65 min on T4 GPU.

In [13]:
import lstm_gat_parallel_model as sparkov_lstm_par

lstm_par_results_sparkov = sparkov_lstm_par.run_all_strategies(df_sparkov, cfg_sparkov)
print('\nSparkov Parallel LSTM‖GAT done.')

############################################################
# LSTM‖GAT (parallel) | multi_relation
############################################################
  Fold 1/5
  [multi_relation] nodes=33,815 edges=352,233 deg(min/med/mean/max)=(6,11.0,10.4,12)
  [multi_relation] nodes=8,094 edges=81,544 deg(min/med/mean/max)=(5,10.0,10.1,11)
     TRAIN | F1 0.956 | P 0.940 | R 0.972 | AUC 0.998 | AP 0.993 | LL 0.0673 | Brier 0.0186
       VAL | F1 0.924 | P 0.943 | R 0.906 | AUC 0.992 | AP 0.977 | LL 0.0956 | Brier 0.0259
  Fold 2/5
     TRAIN | F1 0.963 | P 0.962 | R 0.965 | AUC 0.999 | AP 0.994 | LL 0.0584 | Brier 0.0165
       VAL | F1 0.921 | P 0.930 | R 0.912 | AUC 0.991 | AP 0.973 | LL 0.1211 | Brier 0.0345
  Fold 3/5
     TRAIN | F1 0.949 | P 0.986 | R 0.915 | AUC 0.999 | AP 0.994 | LL 0.0631 | Brier 0.0178
       VAL | F1 0.922 | P 0.960 | R 0.886 | AUC 0.993 | AP 0.976 | LL 0.1462 | Brier 0.0429
  Fold 4/5
     TRAIN | F1 0.957 | P 0.939 | R 0.976 | AUC 0.998 | AP 0.993 | LL 0.0714 | Brier 0.0196
       VAL | F1 0.915 | P 0.911 | R 0.919 | AUC 0.993 | AP 0.973 | LL 0.1217 | Brier 0.0352
  Fold 5/5
     TRAIN | F1 0.963 | P 0.964 | R 0.963 | AUC 0.999 | AP 0.994 | LL 0.0645 | Brier 0.0181
       VAL | F1 0.938 | P 0.939 | R 0.936 | AUC 0.994 | AP 0.981 | LL 0.1039 | Brier 0.0298
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.917 | P 0.942 | R 0.893 | AUC 0.994 | AP 0.978 | LL 0.1062 | Brier 0.0293
  Saved: /content/outcomes/sparkov/sparkov_lstm_gat_par_multi_relation_diagnostics.png

############################################################
# LSTM‖GAT (parallel) | hybrid
############################################################
  Fold 1/5
  [hybrid] nodes=33,815 edges=583,875 deg(min/med/mean/max)=(11,17.0,17.3,28)
  [hybrid] nodes=8,094 edges=137,522 deg(min/med/mean/max)=(12,17.0,17.0,27)
     TRAIN | F1 0.917 | P 0.934 | R 0.901 | AUC 0.992 | AP 0.967 | LL 0.1300 | Brier 0.0346
       VAL | F1 0.873 | P 0.889 | R 0.857 | AUC 0.981 | AP 0.932 | LL 0.1801 | Brier 0.0497
  Fold 2/5
     TRAIN | F1 0.922 | P 0.917 | R 0.928 | AUC 0.993 | AP 0.969 | LL 0.1278 | Brier 0.0345
       VAL | F1 0.875 | P 0.876 | R 0.875 | AUC 0.979 | AP 0.936 | LL 0.1972 | Brier 0.0555
  Fold 3/5
     TRAIN | F1 0.919 | P 0.945 | R 0.894 | AUC 0.993 | AP 0.972 | LL 0.1225 | Brier 0.0333
       VAL | F1 0.879 | P 0.902 | R 0.858 | AUC 0.981 | AP 0.939 | LL 0.1777 | Brier 0.0498
  Fold 4/5
     TRAIN | F1 0.915 | P 0.928 | R 0.902 | AUC 0.991 | AP 0.965 | LL 0.1312 | Brier 0.0354
       VAL | F1 0.867 | P 0.909 | R 0.828 | AUC 0.976 | AP 0.934 | LL 0.1879 | Brier 0.0537
  Fold 5/5
     TRAIN | F1 0.913 | P 0.935 | R 0.892 | AUC 0.991 | AP 0.965 | LL 0.1227 | Brier 0.0332
       VAL | F1 0.881 | P 0.915 | R 0.850 | AUC 0.979 | AP 0.937 | LL 0.1500 | Brier 0.0415
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.869 | P 0.927 | R 0.819 | AUC 0.983 | AP 0.945 | LL 0.1645 | Brier 0.0445
  Saved: /content/outcomes/sparkov/sparkov_lstm_gat_par_hybrid_diagnostics.png

############################################################
# LSTM‖GAT (parallel) | intra_group
############################################################
  Fold 1/5
  [intra_group] nodes=33,815 edges=407,381 deg(min/med/mean/max)=(6,12.0,12.0,18)
  [intra_group] nodes=8,094 edges=97,084 deg(min/med/mean/max)=(6,12.0,12.0,17)
     TRAIN | F1 0.940 | P 0.942 | R 0.938 | AUC 0.996 | AP 0.985 | LL 0.0913 | Brier 0.0251
       VAL | F1 0.908 | P 0.921 | R 0.895 | AUC 0.988 | AP 0.966 | LL 0.1186 | Brier 0.0317
  Fold 2/5
     TRAIN | F1 0.945 | P 0.953 | R 0.938 | AUC 0.997 | AP 0.988 | LL 0.0917 | Brier 0.0259
       VAL | F1 0.905 | P 0.922 | R 0.889 | AUC 0.986 | AP 0.959 | LL 0.1436 | Brier 0.0404
  Fold 3/5
     TRAIN | F1 0.943 | P 0.957 | R 0.931 | AUC 0.997 | AP 0.988 | LL 0.0893 | Brier 0.0254
       VAL | F1 0.915 | P 0.932 | R 0.899 | AUC 0.989 | AP 0.968 | LL 0.1219 | Brier 0.0343
  Fold 4/5
     TRAIN | F1 0.940 | P 0.957 | R 0.924 | AUC 0.996 | AP 0.985 | LL 0.0913 | Brier 0.0249
       VAL | F1 0.912 | P 0.941 | R 0.885 | AUC 0.988 | AP 0.967 | LL 0.1520 | Brier 0.0427
  Fold 5/5
     TRAIN | F1 0.935 | P 0.961 | R 0.911 | AUC 0.997 | AP 0.986 | LL 0.1048 | Brier 0.0299
       VAL | F1 0.923 | P 0.950 | R 0.897 | AUC 0.991 | AP 0.969 | LL 0.1302 | Brier 0.0374
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.913 | P 0.936 | R 0.892 | AUC 0.992 | AP 0.972 | LL 0.1182 | Brier 0.0327
  Saved: /content/outcomes/sparkov/sparkov_lstm_gat_par_intra_group_diagnostics.png

==================================================================================
  Run                              | F1    | P     | R     | AUC   | AP    | Thr
----------------------------------------------------------------------------------
  multi_relation_lstm_gat_par      | 0.917 | 0.942 | 0.893 | 0.994 | 0.978 | 0.852
  hybrid_lstm_gat_par              | 0.869 | 0.927 | 0.819 | 0.983 | 0.945 | 0.801
  intra_group_lstm_gat_par         | 0.913 | 0.936 | 0.892 | 0.992 | 0.972 | 0.803
==================================================================================
  Saved: /content/outcomes/sparkov/sparkov_strategy_comparison.png
  Saved: /content/outcomes/sparkov/sparkov_results_summary.csv

Sparkov Parallel LSTM‖GAT done.

---
## Cell 13 — Sparkov: Homogeneous Account-Level GAT
~5–10 min.

In [14]:
import account_gat_homogeneous_model as sparkov_acct_gat

acct_cfg_sparkov = sparkov_acct_gat.CardAccountConfig()
acct_cfg_sparkov.OUTCOME_DIR = '/content/outcomes/sparkov'

df_accounts_sparkov = sparkov_acct_gat.build_account_dataframe(df_sparkov, acct_cfg_sparkov)
acct_results_sparkov = sparkov_acct_gat.run_all_strategies(df_accounts_sparkov, acct_cfg_sparkov)
print('\nSparkov Homogeneous Account-Level GAT done.')

Aggregating transactions into account-level features...
  999 accounts | fraud rate 0.9770

############################################################
# Homogeneous Account GAT | similarity
############################################################
  Fold 1/5
  [similarity] accounts=639 edges=8,669 deg(min/med/mean/max)=(9,13.0,13.6,29)
  [similarity] accounts=160 edges=2,164 deg(min/med/mean/max)=(9,13.0,13.5,26)
  Early stop at epoch 135
     TRAIN | F1 0.959 | P 1.000 | R 0.921 | AUC 0.992 | AP 1.000 | LL 0.2133 | Brier 0.0659
       VAL | F1 0.991 | P 0.981 | R 1.000 | AUC 0.930 | AP 0.999 | LL 0.0686 | Brier 0.0171
  Fold 2/5
     TRAIN | F1 0.961 | P 0.991 | R 0.933 | AUC 0.911 | AP 0.997 | LL 0.5048 | Brier 0.1713
       VAL | F1 0.994 | P 0.987 | R 1.000 | AUC 0.744 | AP 0.991 | LL 0.4390 | Brier 0.1395
  Fold 3/5
     TRAIN | F1 0.983 | P 0.985 | R 0.981 | AUC 0.926 | AP 0.998 | LL 0.4754 | Brier 0.1616
       VAL | F1 0.994 | P 0.988 | R 1.000 | AUC 0.924 | AP 0.999 | LL 0.3944 | Brier 0.1325
  Fold 4/5
     TRAIN | F1 0.996 | P 0.995 | R 0.997 | AUC 0.997 | AP 1.000 | LL 0.2616 | Brier 0.0706
       VAL | F1 0.981 | P 0.963 | R 1.000 | AUC 0.797 | AP 0.991 | LL 0.5100 | Brier 0.1251
  Fold 5/5
     TRAIN | F1 0.983 | P 0.997 | R 0.970 | AUC 0.991 | AP 1.000 | LL 0.2313 | Brier 0.0671
       VAL | F1 0.990 | P 0.981 | R 1.000 | AUC 0.897 | AP 0.996 | LL 0.1073 | Brier 0.0268
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.992 | P 0.985 | R 1.000 | AUC 0.981 | AP 1.000 | LL 0.1739 | Brier 0.0411
  Saved: /content/outcomes/sparkov/sparkov_account_gat_similarity_diagnostics.png

############################################################
# Homogeneous Account GAT | shared_merchant
############################################################
  Fold 1/5
  [shared_merchant] accounts=639 edges=295,429 deg(min/med/mean/max)=(46,508.0,462.3,615)
  [shared_merchant] accounts=160 edges=18,904 deg(min/med/mean/max)=(17,128.0,118.2,155)
     TRAIN | F1 0.997 | P 0.995 | R 0.998 | AUC 0.993 | AP 1.000 | LL 0.1130 | Brier 0.0159
       VAL | F1 0.997 | P 0.994 | R 1.000 | AUC 0.983 | AP 1.000 | LL 0.4434 | Brier 0.1284
  Fold 2/5
     TRAIN | F1 0.988 | P 0.976 | R 1.000 | AUC 0.978 | AP 0.999 | LL 0.3291 | Brier 0.0993
       VAL | F1 0.994 | P 0.987 | R 1.000 | AUC 0.949 | AP 0.999 | LL 0.8102 | Brier 0.2515
  Fold 3/5
     TRAIN | F1 0.029 | P 1.000 | R 0.014 | AUC 0.912 | AP 0.997 | LL 0.7011 | Brier 0.2540
       VAL | F1 1.000 | P 1.000 | R 1.000 | AUC 1.000 | AP 1.000 | LL 0.6996 | Brier 0.2532
  Fold 4/5
     TRAIN | F1 0.989 | P 0.978 | R 1.000 | AUC 0.599 | AP 0.985 | LL 0.7058 | Brier 0.2563
       VAL | F1 0.981 | P 0.963 | R 1.000 | AUC 0.425 | AP 0.962 | LL 0.7093 | Brier 0.2581
  Fold 5/5
     TRAIN | F1 0.964 | P 0.998 | R 0.931 | AUC 0.990 | AP 1.000 | LL 0.1589 | Brier 0.0378
       VAL | F1 0.997 | P 1.000 | R 0.994 | AUC 0.995 | AP 1.000 | LL 0.0886 | Brier 0.0137
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.992 | P 0.985 | R 1.000 | AUC 0.998 | AP 1.000 | LL 0.5223 | Brier 0.1673
  Saved: /content/outcomes/sparkov/sparkov_account_gat_shared_merchant_diagnostics.png

############################################################
# Homogeneous Account GAT | combined
############################################################
  Fold 1/5
  [combined] accounts=639 edges=297,575 deg(min/med/mean/max)=(55,510.0,465.7,615)
  [combined] accounts=160 edges=19,400 deg(min/med/mean/max)=(26,131.0,121.2,155)
  Early stop at epoch 165
     TRAIN | F1 0.483 | P 1.000 | R 0.318 | AUC 0.944 | AP 0.998 | LL 0.6462 | Brier 0.2333
       VAL | F1 0.997 | P 0.994 | R 1.000 | AUC 0.985 | AP 1.000 | LL 0.6602 | Brier 0.2336
  Fold 2/5
     TRAIN | F1 0.990 | P 0.981 | R 1.000 | AUC 0.992 | AP 1.000 | LL 0.4187 | Brier 0.1376
       VAL | F1 0.994 | P 0.987 | R 1.000 | AUC 0.986 | AP 1.000 | LL 1.0745 | Brier 0.3282
  Fold 3/5
     TRAIN | F1 0.990 | P 0.995 | R 0.986 | AUC 0.954 | AP 0.998 | LL 0.2282 | Brier 0.0577
       VAL | F1 0.997 | P 0.994 | R 1.000 | AUC 0.994 | AP 1.000 | LL 0.2351 | Brier 0.0596
  Fold 4/5
     TRAIN | F1 0.963 | P 1.000 | R 0.928 | AUC 0.989 | AP 1.000 | LL 0.1519 | Brier 0.0406
       VAL | F1 0.981 | P 0.963 | R 1.000 | AUC 0.874 | AP 0.994 | LL 0.1494 | Brier 0.0349
  Fold 5/5
     TRAIN | F1 0.988 | P 0.977 | R 1.000 | AUC 0.648 | AP 0.986 | LL 0.7358 | Brier 0.2713
       VAL | F1 0.984 | P 0.969 | R 1.000 | AUC 0.783 | AP 0.991 | LL 0.7456 | Brier 0.2762
  Test fold 1/5...
  Test fold 2/5...
  Test fold 3/5...
  Test fold 4/5...
  Test fold 5/5...
      TEST | F1 0.992 | P 0.985 | R 1.000 | AUC 0.997 | AP 1.000 | LL 0.4590 | Brier 0.1393
  Saved: /content/outcomes/sparkov/sparkov_account_gat_combined_diagnostics.png

==================================================================================
  Run                              | F1    | P     | R     | AUC   | AP    | Thr
----------------------------------------------------------------------------------
  similarity_account_gat           | 0.992 | 0.985 | 1.000 | 0.981 | 1.000 | 0.003
  shared_merchant_account_gat      | 0.992 | 0.985 | 1.000 | 0.998 | 1.000 | 0.044
  combined_account_gat             | 0.992 | 0.985 | 1.000 | 0.997 | 1.000 | 0.012
==================================================================================
  Saved: /content/outcomes/sparkov/sparkov_strategy_comparison.png
  Saved: /content/outcomes/sparkov/sparkov_results_summary.csv

Sparkov Homogeneous Account-Level GAT done.

---
## Cell 14 — Sparkov: combined comparison table

In [15]:
all_results_sparkov = {}
all_results_sparkov.update(gatv2_results_sparkov)
all_results_sparkov.update(lstm_seq_results_sparkov)
all_results_sparkov.update(lstm_par_results_sparkov)
all_results_sparkov.update(acct_results_sparkov)

rows = []
for key, res in all_results_sparkov.items():
    m = res['test_metrics']
    rows.append({'run': key, 'model_arch': res.get('model_arch', ''),
                 'graph_strategy': res.get('graph_strategy', ''),
                 'f1': round(m['f1'], 4), 'prec': round(m['prec'], 4), 'rec': round(m['rec'], 4),
                 'auc': round(m['auc'], 4), 'ap': round(m['ap'], 4)})

df_summary_sparkov = pd.DataFrame(rows).sort_values(['model_arch', 'f1'], ascending=[True, False])
os.makedirs('/content/outcomes/sparkov', exist_ok=True)
df_summary_sparkov.to_csv('/content/outcomes/sparkov/all_architectures_summary.csv', index=False)
df_summary_sparkov

,run,model_arch,graph_strategy,f1,prec,rec,auc,ap
9,similarity_account_gat,account_gat,similarity,0.9924,0.9850,1.0000,0.9814,0.9997
10,shared_merchant_account_gat,account_gat,shared_merchant,0.9924,0.9850,1.0000,0.9983,1.0000
11,combined_account_gat,account_gat,combined,0.9924,0.9850,1.0000,0.9966,0.9999
2,intra_group_gatv2,gatv2,intra_group,0.9098,0.9431,0.8788,0.9918,0.9714
0,multi_relation_gatv2,gatv2,multi_relation,0.9088,0.9569,0.8653,0.9943,0.9782
1,hybrid_gatv2,gatv2,hybrid,0.8623,0.9124,0.8175,0.9826,0.9418
6,multi_relation_lstm_gat_par,lstm_gat_par,multi_relation,0.9172,0.9424,0.8934,0.9940,0.9776
8,intra_group_lstm_gat_par,lstm_gat_par,intra_group,0.9135,0.9357,0.8924,0.9921,0.9723
7,hybrid_lstm_gat_par,lstm_gat_par,hybrid,0.8694,0.9270,0.8185,0.9835,0.9448
5,intra_group_lstm_gat_seq,lstm_gat_seq,intra_group,0.9438,0.9582,0.9298,0.9972,0.9886
3,multi_relation_lstm_gat_seq,lstm_gat_seq,multi_relation,0.9355,0.9683,0.9048,0.9969,0.9878
4,hybrid_lstm_gat_seq,lstm_gat_seq,hybrid,0.9131,0.9620,0.8690,0.9939,0.9792

---
## Cell 15 — Download everything

In [16]:
!cd /content/outcomes && zip -qr /content/outcomes.zip .
from google.colab import files
files.download('/content/outcomes.zip')

In [17]:
!grep -n "GATv2Conv\|GATConv" /content/hybrid-gnn-lstm-fraud/ibm/lstm_gat_parallel_model.py
!grep -n "lstm_hidden = lstm_hidden or" /content/hybrid-gnn-lstm-fraud/sparkov/lstm_gat_sequential_model.py
!grep -n "lstm_hidden = lstm_hidden or" /content/hybrid-gnn-lstm-fraud/sparkov/lstm_gat_parallel_model.py

30:from torch_geometric.nn import GATv2Conv
153:        self.gat1 = GATv2Conv(in_dim, hidden, heads=heads, dropout=dropout)
154:        self.gat2 = GATv2Conv(hidden*heads, hidden, heads=heads, dropout=dropout)
112:        lstm_hidden = lstm_hidden or 64
120:        lstm_hidden = lstm_hidden or 64